### ISSUE TITLE
Add tab to manage outdated agents and upgrade via WPK

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-dashboard-plugins#3107]
**Describe the solution you'd like**

It would be useful to have a tab that could be used to check if any agent is outdated and upgrade them if necessary.

Currently, this can be done by using the `Dev Tools` console and running the corresponding API calls, 
https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/agent-upgrade-module.html
but it would be nice to have a more convenient and intuitive way of doing this.

**Comment by CPAlejandro** [comment]
As an idea for its development, he had thought of adding two options:
- In the `agents table`, in the `actions` part, add a button with the shape of an upward arrow, in the same style as the ones that already exist, which can only be selected if it is an agent that can be updated to a more current version .
-Add an option, such as `deploy new agent`, which is update old agents, which opens a submenu (as in `explore agents`) where only the agents that can be updated appear and an icon next to them to select them and an option to mark all, to be able to update as many as you want at once

**Comment by CPAlejandro** [comment]
**Current feedback**
Created a button to update a particular outdated agent and created a button that takes you to the view to be able to delete several agents at the same time in the agents overview.
Still creating said view.

**Comment by CPAlejandro** [comment]
**Current feedback**
Adapting from the PR the buttons to update, refresh or delete an agent, both in the agent table:
![image](https://user-images.githubusercontent.com/17100196/115574116-a543bd80-a2c1-11eb-88af-fff3fc87ce43.png)
And in its own section.
![image](https://user-images.githubusercontent.com/17100196/115574320-cefce480-a2c1-11eb-82f5-12a9785171c2.png)

**Comment by CPAlejandro** [comment]
**Today's Feedback**
Refactored functions that did the same to update, delete or restart an agent.
_Pending tasks:_
- Fix when clicking on select all agents, which breaks the table
- Add the icon next to the version, when an agent is updated, know if it continues to update or has finished the update in error.
- To be able to go to another page of agents and when we return to where we were, have the same checks that we had

**Comment by CPAlejandro** [comment]
**Current feedback**
- Refactored several functions that generated a lot of errors again, finally having 2 that control the behavior of the 3 buttons
- Resolved error that caused the restart or update buttons to not be shown in the section of each agent, when it should
- Trying to solve the problems that are generated in the table when pressing the select all agents button and the problem that when you go to another page, the agents you had marked are lost

**Comment by CPAlejandro** [comment]
**Current feedback**
- Including the filters created previously or at the moment to the table, to be able only to select the agents according to those filters
- Working on refactoring the table to create it by rows to achieve that when changing pages and returning, continue with the marked checks that we had before.
- Working on the inclusion of the button to know if the update of an agent is still in process or has finished properly / failing

**Comment by AlexRuiz7** [comment]
Superseded by https://github.com/wazuh/wazuh-dashboard-plugins/issues/6141
