### ISSUE TITLE
App settings: Values of `wazuh.monitoring.enabled` not correctly managed

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#3624]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

**Description**
The `wazuh.monitoring.enabled` app setting according to the [documentation](https://documentation.wazuh.com/current/user-manual/kibana-app/reference/config-file.html?highlight=when%20value%20set%20worker#monitoring) can take three controlled values: `true`, `false`, `worker`. For the `worker` case the `Evolution` visualization should be visible and the `monitoring` job should be disabled, but in the [source code for the visualization](https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/controllers/agent/components/agents-preview.js#L88-L98) only is checking the value for the setting is truthy (evaluation to `true`.

Moreover, the setting can't be configurated to the `worker` value because its control is a switch of 2 possible values 
![image](https://user-images.githubusercontent.com/34042064/134497698-5c5ad3ba-f76b-4205-a6b4-411c3f2487cb.png)

**Tasks**
- [ ] Evaluate how we want to manage this setting if we want to keep the 3 values or only 2 (to control if the job is running or not)
- [ ] Apply the required fixes

**Acceptance criteria**
- Define the strategy to apply and modify the app according to the decision

**Note**
This issue could be affected by https://github.com/wazuh/wazuh-kibana-app/issues/3623

**Comment by Desvelao** [comment]
We could think to create a new setting to get the same case of when the value is `worker`.

**Comment by gdiazlo** [comment]
We're deprecating this setting in the next major release.
