### ISSUE TITLE
Show a shortcut to `Reports` when a PDF report is generated.

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-dashboard-plugins#3936]
**Describe the solution you'd like**
Add a shortcut (link) to the Report section on the information toast that pops up when a PDF report is generated.

![image](https://user-images.githubusercontent.com/15186973/161076057-9e23c057-673f-4487-9d72-6d439a1fbf3b.png)

**Describe alternatives you've considered**
-

**Additional context**
This is present on our Splunk app. I think this is an interesting feature that will save time to our users.

**Comment by Desvelao** [comment]
This ability was added in 4.9.0, see: https://github.com/wazuh/wazuh-dashboard-plugins/pull/6558.

I will close the issue.
