### ISSUE TITLE
Browser hangs when long JSON responses are collapsed on API Console

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-dashboard-plugins#4226]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.4   | 7.10.2     | 4305 | - |

| Browser |
| ------- |
| Chrome, Firefox|

**Preconditions**
1. Wazuh Dasboard access

**Steps to reproduce**
1. Login to Wazuh Dashboard
2. Go to Toolst > API Console
4. Make a GET request to the MITRE API endpoint: `GET /mitre/software?pritty=true`

**Expected Result**
1. A big response is obtained. Collapsing or manipulating the JSON response is fluent

**Actual Result**
1. A big response is obtained. Collapsing or manipulating the JSON response hangs the browser, showing a hint about this slow down

**Screenshots**

![image](https://user-images.githubusercontent.com/1791430/172387286-6b7cacc2-98be-475a-980f-71e6f30ed2bd.png)

**Comment by pro-akim** [comment]
It was not replicated in 
- https://github.com/wazuh/wazuh/issues/18828
