### ISSUE TITLE
Use platform editor component instead of our own

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard-plugins#5039]
**Describe the solution you'd like**

Evaluate if we can reuse the platform editor instead of our own as an editor component.

**Additional context**

This will allow us to use less dependencies.

- [CodeQL#11](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/11)
- [CodeQL#10](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/10)
- [CodeQL#9](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/9)

**Related issues**
- [x] #4816
- [ ] #3659
- [x] #3504

**Comment by yenienserrano** [comment]
Currently, `opensearch/oui` in the `ouiCodeEditor` component is using `Ace`, and they are going to deprecate the component, while `opensearch dashboard` can use `Monaco` as an option, but they have version `0.17.1` and `Monaco` is already on version `0.36.1`. 

They have this [issue](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3097) to update Monaco in 2.7.0

And in OUI they have this [issue](https://github.com/opensearch-project/oui/issues/92) that from what I understand is not a priority for them, the code editor component.

I have been testing the Monaco implementation offered by Opensearch, but I can't get the formatting right.

Monaco
![image](https://user-images.githubusercontent.com/63758389/222209513-005aee52-8f81-4d51-b079-42d4c5547590.png)

EuiCodeEditor
![image](https://user-images.githubusercontent.com/63758389/222209872-8f5edcd1-9ebf-4cf8-8e83-59adee44c983.png)

**Comment by yenienserrano** [comment]
Looking at the opensearch code, I saw that they still have the `Ace` plugin, but they [deprecated](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/packages/osd-ace/README.md?plain=1#L14-L20) it and suggest you to use `Monaco`.

And I also saw that you intend to add [more information](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2132) about Monaco.

**Comment by yenienserrano** [comment]
I have seen that the custom version of monaco offered in opensearch uses react-monaco-editor in addition to monaco-editor, and I created a new project to see how it works and by default the same thing happens to me, it does not look with styles, so I am testing to see what configuration would be the most appropriate for the project.



![Image](https://user-images.githubusercontent.com/63758389/222495428-1aaad753-de31-4e31-ba89-1182615f4056.png)

**Comment by yenienserrano** [comment]
Reviewing the implementation of Moncaco that offers OSD I saw that it does not give much variety of languages, maybe it is because of the version that uses that is 0.17.1 and goes by the 0.36.1, or maybe in its modifications only let see those languages.

![Image](https://user-images.githubusercontent.com/63758389/222780951-683d8d90-520f-45d6-aa59-eb1ec48294e4.png)

**Comment by yenienserrano** [comment]
I created this [issue](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3528) in the OpenSerach Dashboards repository, and they replied that you have to add the file with the language you want to add.

I was testing, and we would have to first integrate the language and then make the change from the current editor to the one that OpenSearch Dashboard tested.

![Image](https://user-images.githubusercontent.com/63758389/223480017-f307fc3c-d03d-4dcb-a14a-3679de546912.png)

![Image](https://user-images.githubusercontent.com/63758389/223479154-8a00b236-a629-43da-82c9-2369870cf4f4.png)

**Comment by yenienserrano** [comment]
I share the file with the one I managed to make it look similar, but it needs to be finished.


[xml.txt](https://github.com/wazuh/wazuh-kibana-app/files/10911594/xml.txt)

**Comment by Desvelao** [comment]
These problems
> This will allow us to use less dependencies.

> - [CodeQL#11](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/11)
> - [CodeQL#10](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/10)
> - [CodeQL#9](https://github.com/wazuh/wazuh-kibana-app/security/code-scanning/9)

is related to the `codemirror`. This editor is used in the API Console.

For this case, and due to the syntax and behavior being similar to the `Console`, we could review the implementation and see how is built the editor.

**Comment by gdiazlo** [comment]
This has been superseded by other issues.
