### ISSUE TITLE
Redesign agent view

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-dashboard-plugins#5050]
## Summary

Update the "agent view". Currently, we have:

![image](https://user-images.githubusercontent.com/63758389/209973785-204e1adb-dc2f-41d6-af42-b6bc45a46f50.png)

## Requirements

We need:
- [x] #5051
- [ ] See if the columns "Registration date" and "Last keep alive" are necessary, if not, remove them from the table.
- [ ] See if we are satisfied with the way the agent groups are being shown in the table.

Parent issue:
- https://github.com/wazuh/wazuh/issues/11011

**Comment by gdiazlo** [comment]
Superseed by the fleet management issue:
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6129
