### ISSUE TITLE
Tabs names of Settings section are hardly visible

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#5117]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Wazuh dashboard |

| Browser |
| ------- |
| Firefox|

**Description**
The tab names are hardly visibles using Firefox.

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to Settings section
2. See the color of tab names

**Expected Result**
1. 

**Actual Result**
1. 

**Screenshots**
Firefox 103.0.1
![image](https://user-images.githubusercontent.com/34042064/212302299-83ea9223-77a9-40d9-9f95-17c8e3e16d38.png)

Compare to other sections with tabs:
![image](https://user-images.githubusercontent.com/34042064/212302752-5871bc9c-67a9-49be-9e22-3a8e4638d0e4.png)
![image](https://user-images.githubusercontent.com/34042064/212302845-9e349480-974b-4f75-8e2a-c786b984dc5b.png)
![image](https://user-images.githubusercontent.com/34042064/212303015-068586c7-8d25-4725-a913-0c46f14b382b.png)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by JuanGarriuz** [comment]
### Test 24/12/2024

Firefox 133.0.3

![Image](https://github.com/user-attachments/assets/72dee923-a12b-47b8-ab20-185489df536a)

![Image](https://github.com/user-attachments/assets/1fea82e5-3352-4abf-a6c3-ff99be4781ea)



![Image](https://github.com/user-attachments/assets/70464094-e232-4f74-8626-4e4225c23a04)

**Comment by asteriscos** [comment]
This issue no longer applies.

**Comment by Desvelao** [comment]
App Settings tabs in Firefox for Wazuh dashboard 4.9.2
![Image](https://github.com/user-attachments/assets/41f35416-6fe1-4a25-b436-7b7b597c49e0)

It seems the problem could be already resolved.
