### ISSUE TITLE
Office365 and Github Panel drilldown filter doesn't clear

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#5215]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.10   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
**The first time** a user enters the Panel tab in Office365 or Github, and clicks on a row value to drilldown the information, it adds 2 filters instead of the selected one

**Preconditions**
1. Tested with Sample data

**Steps to reproduce**
1. Navigate to Office365 module -> Panel tab
2. Click on a user value to access the drilldown
3. Click on the Back arrow button
4. Click on a Top Client IP value to drilldown on another filter field
5. See both filters applied

**Expected Result**
1. The drilldown should only add its own field filter

**Actual Result**
1. The drilldown adds both own field filter and the previously selected one

**Screenshots**
![Peek 2023-02-17 13-41](https://user-images.githubusercontent.com/9343732/219685471-1e52a7b0-c858-4f8a-b557-650952441e91.gif)

## Potential fix

Applying these changes in the [public/components/common/hooks/use-filter-manager.ts](https://github.com/wazuh/wazuh-kibana-app/pull/5191/files#diff-eca6c43830800c1c00410eee4e42aa0c95f9c077c26af0f00a36e0b2379c6dc3) could fix this issue.

**Comment by JuanGarriuz** [comment]
###  Test 24/12/2024

https://github.com/user-attachments/assets/765d2787-4e5c-40d0-9846-5b36b149ad9c
https://github.com/user-attachments/assets/6e46d861-aef1-4645-b65b-add7ddb3c2c0

It can be closed

**Comment by asteriscos** [comment]
I'll close this issue then.
