### ISSUE TITLE
Error in Wazuh Dashboard when displaying CDB list

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#5259]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Saving keys wrapped with double quotes are not displayed properly after restarting the manager. Only the double quote at the start exists,

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to _Management -> CDB Lists_
2. Add a new key to a CDB List
3. Restart the Manager
4. Refresh the browser tab

**Screenshots**

![image](https://user-images.githubusercontent.com/9343732/222790043-cff6f303-19cf-4196-af9b-5e76e7606a30.png)

![image](https://user-images.githubusercontent.com/9343732/222790067-7b0a399e-0b44-47e1-81a9-8c4cf24d272e.png)

But checking after restarting the manager, the quotation mark at the beginning is observed:
![image](https://user-images.githubusercontent.com/9343732/222790084-e004c4fc-a98b-4bcc-b6fc-85ffe6b56d95.png)

Checking via CLI, the record is properly displayed:
![image](https://user-images.githubusercontent.com/9343732/222790190-c2b1c66b-f186-4514-baa7-ae0a066a78e6.png)

And this generates an error when a new key is added:
![image](https://user-images.githubusercontent.com/9343732/222790270-a308aeb3-37b0-4cc6-a7f7-9bf274ca41a8.png)

**Comment by Desvelao** [comment]
Related issue: https://github.com/wazuh/wazuh-kibana-app/issues/5064

**Comment by JuanGarriuz** [comment]
Fixed on #7154
