### ISSUE TITLE
`wazuh.yml` allows multiple hosts with the same ID

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-dashboard-plugins#5422]
## Description

The `hosts` field in the `wazuh.yml` is currently an array, which allows duplicated values. This is a problem as several hosts can be configured using the same ID, causing confusion on the UI.

On one hand, it breaks the UI API selector, as from those hosts with the same ID, the first one is always selected. Basically, it's impossible to select any other host with the same name.
On the other hand, it's confusing for the user, as it's not clear which host is currently selected, as every host with the same ID is marked as selected.

**Preconditions**
1. The `wazuh.yml` has several hosts with the same name (ID).

**Steps to reproduce**
1. Navigate to the UI.
2. Click on the API selector.
3. Check that no other host with the same name can be selected

1. Navigate to Settings > API configuration.
2. Check that every API with the same name is marked as selected.

**Screenshots**

**Additional context**
This is a problem of design. The `hosts` field should be an object (key-value pairs), as it will prevent the addition of hosts with the same name (key) natively in YAML format.

**Comment by gdiazlo** [comment]
We're deprecating  this file in the next major release.
