### ISSUE TITLE
Wazuh should collect the external IPv4 and IPv6 addressses employed by agents

### ISSUE THREAD

**Issue by fernandogont** [wazuh/wazuh-dashboard-plugins#5701]
## Description
In the IPv4 world, a lot of deployments imply that Wazuh agents will connect to the Wazuh server via a NAT (one or multiple instances). While syscollector collects the local addresses configured at the host running the Wazuh agent, these addresses are usually not very meaningful for security operations purposes.

My proposal is that Wazuh collects/learns the *public* IPv4 and  IPv6 addresses employed by Wazuh agents. There's at least two possible ways to do it:

* Have the wazuh server collect/learn this addresses -- i.e., this is the address(es) that the wazuh server sees when the agent connects to it, or,
* Have e.g. syscollector query e.g. "curl ifconfig.me" to learn its external addresses

## Tasks
The steps that have to be completed in order to close the issue.

This will depend on the strategy, as discussed above.

## Additional information
Add here any additional information relevant to the issue or that will help to close it: chunks of code, logs, additional error messages, related issues and so on.

**Comment by yenienserrano** [comment]
Hi I understand that you want to use IPV6 right? You can connect the agents with IPV6 since version 4.4.

https://wazuh.com/blog/introducing-wazuh-4-4/

**Comment by yenienserrano** [comment]
Closed for inactivity

**Comment by fgont** [comment]
What I was meaning is that the external IP address should be colleved and be provided as part of the inventory.
e.g., you could have agents connect via both IPv4 and IPv6, and at least record those two IP addresses such that they become part of the inventory.
