### ISSUE TITLE
Update the new sidebar menu design

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#5893]
**Description**

A new sidebar menu design was defined in a recent meeting.

We got a new sidebar menu defined in a recent meeting. There are some changes that we should apply to the previous design.

# Requirements update

| Category | Name | ID | Section in monolith plugin | Changes |
|---|---|---|---|---|
| Home | Overview | wz-home | Modules directory | This is the home (the home icon) |
| Endpoint security | Security Configuration Assessment | security-configuration-assessment | Modules > Security Configuration Assessment | RENAME Configuration assessment |
| Endpoint security | Policy monitoring | policy-monitoring | Modules > Policy monitoring | RENAME to Malware detection  (this is rootcheck now) |
| Endpoint security | Integrity monitoring | integrity-monitoring | Modules > Integrity monitoring | RENAME to File integrity monitoring |
| Endpoint security | System auditing | system-auditing | Modules > System auditing | DELETE |
| Endpoint security | OpenSCAP | openscap | Modules > OpenSCAP | DELETE |
| Endpoint security | CIS-CAT | ciscat | Modules > CIS-CAT | DELETE |
| Threat intelligence | Security events | security-events | Modules > Security events | RENAME Threat hunting |
| Threat intelligence | Vulnerabilities | vulnerabilities | Modules > Vulnerabilities | RENAME to Vulnerability detection |
| Threat intelligence | MITRE ATT&CK | mitre-attack | Modules > MITRE ATT&CK | |
| Threat intelligence | Virustotal | virustotal | Modules > Virustotal | |
| Security operations | PCI DSS | pci-dss | Modules > PCI DSS | |
| Security operations | GDPR | gdpr | Modules > GDPR | |
| Security operations | HIPAA | hipaa | Modules > HIPAA | |
| Security operations | NIST 800-53 | nist-800-53 | Modules > NIST 800-53 | |
| Security operations | TSC | tsc | Modules > TSC | |
| Security operations | IT Hygiene | it-hygiene | Agents > {agent_id} -> Inventory |  |
| Security operations | Osquery | osquery | Modules > Osquery | DELETE |
| Cloud security | AWS | amazon-web-services | Modules > AWS | |
| Cloud security | Google Cloud | google-cloud | Modules > Google Cloud | |
| Cloud security | GitHub | github | Modules > GitHub | |
| Cloud security | Office365 | office365 | Modules > Office365 | |
| Cloud security | Docker listener | docker-listener | Modules > Docker listener | RENAME to Docker |
| Explore | Discover | - | - | Renamed from "Openseach dashboards" |
| Explore | Dashboards | - | - | |
| Explore | Visualize | - | - | |
| Explore | Reporting | - | - | Comes from "Opensearch plugins"  |
| Explore | Alerting | - | - | |
| Explore | Maps | - | - | |
| Explore | Notifications | - | - | |
| Server management | Endpoints summary | endpoints-summary | Agents | This comes from Endpoint security |
| Server management | Groups | groups | Management > Groups | RENAME to Endpoint groups |
| Server management | Rules | rules | Management > Rules | |
| Server management | Decoders | decoders | Management > Decoders | |
| Server management | CDB lists | cdb-lists | Management > CDB lists | |
| Server management | Status | server-status | Management > Status | |
| Server management | Cluster | cluster | Management > Cluster | |
| Server management | Statistics | statistics | Management > Statistics | |
| Server management | Logs | logs | Management > Logs | |
| Server management | Settings | settings | Management > Configuration | |
| Server management | API console | api-console | Tools > API console | RENAME Dev tools |
| Server management | Ruleset test | ruleset-test | Tools > Ruleset test | |
| Server management | RBAC | rbac | Security | RENAME to Security |
| Indexer/dashboard Management | Reporting | reporting | Management > Reporting | Comes from "server management" | REMOVE and use Explore reporting highjacking the download capability of the standard plugin |
| Indexer/dashboard Management | Server API | server-api | Settings > API configuration | |
| Indexer/dashboard Management | Modules | modules | Settings > Modules | DELETE |
| Indexer/dashboard Management | Server data | server-data | Settings > Sample data | |
| Indexer/dashboard Management | Configuration | configuration | Settings > Configuration | RENAME to Wazuh plugin settings |
| Indexer/dashboard Management | Logs | app-logs | Settings > Logs | RENAME to Wazuh plugin logs |
| Indexer/dashboard Management | About | about | Settings > About | RENAME to Wazuh plugin about |
| Indexer/dashboard Management | Dev tools | - | - | Comes from management |
| Indexer/dashboard Management | Stack management | - | - | Comes from management |
| Indexer/dashboard Management | Security | - | - | -> Comes from Opensearch plugins, nice to move it to indexer./dashaboard management  |
| Indexer/dashboard Management| Index management | - | - | |
| Indexer/dashboard Management | Snapshot management | - | - | |

Tasks
- [x] Update the sidebar with the new design
- [x] Adapt the agent menu to the applications related to the agent
- [ ] Move the built-in applications to the expected category
- [x] Enhance the order of applications

**Comment by Desvelao** [comment]
# Considerations
- The applications called `Wazuh plugin <placeholder>` use the branding name. We should remove the branding name so these doesn't have to be modified for users that want to customize the Wazuh dashboard.

**Comment by Desvelao** [comment]
The changes that are not related to the Wazuh applications must be changed by editing the source code of Wazuh dashboard package.

I saw that OpenSearch Dashboards 2.9.0 includes some applications that are not specified in the desired design for Wazuh dashboard. We should decide what to do.

![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/7ee63222-9b22-4e4d-9783-b22172821644)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/5b0b35a1-efc4-46dd-871d-b4c484a607b3)

In 2.9.0, the `Security` is under the `Management` category.

For another hand, in OpenSearch Dashboards 2.9.0 the `Stack management` application was renamed to `Dashboards management`. If we change the name of the category this belongs to, from `Management` to `Indexer/dashboard management` this could be redundant.

**Comment by Desvelao** [comment]
OpenSearch Dashboards 2.10.0 was released recently.

These are the applications that are visible in the side menu:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/91b5e362-3c93-42ed-8210-5be7b0c78b6a)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/212efa60-c600-49fa-892d-c7ea2fd062fd)

**Comment by Desvelao** [comment]
I am working on the required changes to the built-in applications according to the current design. In the following days, there will be a meeting to discuss the desired applications for the Wazuh dashboard.

We will need to know the order within the categories.

**Comment by JuanGarriuz** [comment]
I created a patch to remove wazuh_modules searching for a more reusable app.
[Patch to remove WAZUH_MODULES](https://github.com/wazuh/wazuh-kibana-app/files/12791942/remove-wazuh-modules-end.patch)
