### ISSUE TITLE
Release 4.7.0 - Alpha 1 - Wazuh UI regression testing

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-dashboard-plugins#6000]
## Wazuh UI tests information
|                                        |     |
|----------------------------------------|-----|
| **Version**                            |   4.7.0  |

## Test report procedure

**TL;DR**
   1. The specified tests will be executed in every platform and version mentioned in this issue.
   1. Include evidence of each test performed.
   1. Report any problem or bug. Open a new issue for each of them and link them here.
   1. Justify skipped tests.

All test results must have one the following statuses: 
|                 |                                                                      |
|-----------------|----------------------------------------------------------------------|
| :black_circle:  | The test hasn't started yet.                                         |
| :green_circle:  | All checks passed.                                                   |
| :red_circle:    | There is at least one failed check.                                  |
| :yellow_circle: | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause.
It must be included in the `Problems` section of the current release candidate issue.

Any expected fail or skipped test must be justified with a reason. 
All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip, txt or images. 
This report can be used by the auditors to dig deeper into any possible failures and details.

## Test plan

1. Verify the app package installs and operates as expected.
2. https://github.com/wazuh/wazuh-dashboard-plugins/issues/5678
3. https://github.com/wazuh/wazuh-dashboard-plugins/issues/5175
4. https://github.com/wazuh/wazuh-dashboard-plugins/issues/5662
5. https://github.com/wazuh/wazuh-dashboard-plugins/issues/5051
6. https://github.com/wazuh/wazuh-dashboard-plugins/issues/5493
7. https://github.com/wazuh/wazuh-dashboard-plugins/issues/5258
8. https://github.com/wazuh/wazuh-dashboard-plugins/issues/5529
9. https://github.com/wazuh/wazuh-dashboard-plugins/issues/5267
10. https://github.com/wazuh/wazuh-dashboard-plugins/issues/5617
11. https://github.com/wazuh/wazuh-dashboard-plugins/issues/5219

## Conclusions

| Status         | Test |  Comments |
|----------------|--------------------------------|-----------|
| :green_circle: | Verify the app package installs and operates as expected |      |
| :green_circle: | https://github.com/wazuh/wazuh-dashboard-plugins/issues/5678 |      |
| :green_circle: | https://github.com/wazuh/wazuh-dashboard-plugins/issues/5175 |      |
| :red_circle: | https://github.com/wazuh/wazuh-dashboard-plugins/issues/5662 |   New issue opened: https://github.com/wazuh/wazuh-dashboard-plugins/issues/6016   |
| :yellow_circle: | https://github.com/wazuh/wazuh-dashboard-plugins/issues/5051 | New issue opened:  https://github.com/wazuh/wazuh/issues/19721   |
| :green_circle: | https://github.com/wazuh/wazuh-dashboard-plugins/issues/5493 |      |
| :green_circle: | https://github.com/wazuh/wazuh-dashboard-plugins/issues/5258 |      |
| :green_circle: |  https://github.com/wazuh/wazuh-dashboard-plugins/issues/5529 |      |
| :green_circle: | https://github.com/wazuh/wazuh-dashboard-plugins/issues/5267 |      |
| :green_circle: | https://github.com/wazuh/wazuh-dashboard-plugins/issues/5617 |      |
| :green_circle: | https://github.com/wazuh/wazuh-dashboard-plugins/issues/5219 |      |

All tests have passed and the fails have been reported or justified. I therefore conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @wazuh/frontend 
- [ ] @damarisg

**Comment by Tostti** [comment]
## :green_circle: Verify the app package installs and operates as expected. 
<details>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/1b0d1b10-d908-401c-b6f3-0266e5554185)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/5a1e585e-04a1-4f27-9c71-501c262a694a)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/1cddf818-29f9-4e4c-a3ff-da39d9183276)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/bcff9d79-cf52-42cc-be7b-026262bf1770)

</details>

## :black_circle: https://github.com/wazuh/wazuh-dashboard-plugins/issues/5678
<details>

</details>

## :green_circle: https://github.com/wazuh/wazuh-dashboard-plugins/issues/5175
<details>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/aebfda1f-7d70-4225-95e7-af3a589b26f6)

</details>

## :red_circle: https://github.com/wazuh/wazuh-dashboard-plugins/issues/5662
<details>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/a054e375-ab2d-4b1f-8a11-b20d3affe199)

</details>


## :yellow_circle: https://github.com/wazuh/wazuh-dashboard-plugins/issues/5051
<details>

It shows the tooltip, but it always says `Without information`

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/60742643-1298-43ce-803a-06cbb29bd205)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/cd667d86-6b72-437b-a1e8-4a74ee85855f)

</details>

## :green_circle: https://github.com/wazuh/wazuh-dashboard-plugins/issues/5493
<details>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/927fafd3-b5b3-4783-aeac-5781f61a51ef)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/bd110da1-b9c1-48db-be89-382e2bc01cee)

</details>

## :black_circle: https://github.com/wazuh/wazuh-dashboard-plugins/issues/5258
<details>


</details>

## :black_circle: https://github.com/wazuh/wazuh-dashboard-plugins/issues/5258
<details>


</details>

**Comment by yenienserrano** [comment]
LGTM!

**Comment by damarisg** [comment]
LGTM
