### ISSUE TITLE
Bad performance of agent evolution chart

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#6007]
**Description**
Some environments with the monitoring task enabled and heavy load of data is experiencing problems in the Agents dashboard.

The requests to display the Agents evolution visualization or the most active agent KPI are too slow and can break the UI due to failing or timeouts.

These environments have no way to avoid this problem of performance when the monitoring task is enabled.

We did some work around this topic, but it was finally added because the solution was a breaking change https://github.com/wazuh/wazuh-dashboard-plugins/issues/4388.

The data stored in the `wazuh-monitoring-*` indices is indexed by the monitoring task of the plugin. Some users are using this data to create custom visualizations or retrieve information.

**Comment by gdiazlo** [comment]
We will address this in 
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6129
-
