### ISSUE TITLE
Incorrect agent name validation: numeric characters should be allowed

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-dashboard-plugins#6029]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
|4.6.0 | 02 |  Firefox |

**Description**

The new 'Deploy new agents' section is incorrectly validating agent names by not allowing numeric characters. This issue was introduced in version 4.6.0. 

As can be seen in the screenshots, the 'Deploy new agent' section incorrectly states 'Server2' is an invalid name, even though it's valid. In the following image, you can see that the 'Server2' agent is successfully registered and connected. 

The allowed characters are: alphanumeric characters, `-`, `_` or `.`. See the [agent_name](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#enrollment-agent-name) reference for more details. 

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/61882981/5497331e-785c-401f-9382-37f1018545e4)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/61882981/b9d6eb02-3a0e-4991-ae1b-2a1bb1168dc5)

**Comment by Tostti** [comment]
PR Successfully merged

**Comment by Desvelao** [comment]
Workaround to using numbers in the agent name for Wazuh plugins that give a validation error:

Use a valid name in the form of the deploy new agent guide to allow the command to deploy the agent available. Then copy the provided command to install the agent and add the wanted numbers to the `WAZUH_AGENT_NAME` environment variable that defines the agent name before running the command in the host where you will deploy the agent.
