### ISSUE TITLE
Security events dashboard filter is not updating events list

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6042]
# Description 

In the security events dashboard, when user types a rule ID number he gets the updates on the dashboard and the list of events as shown below

When clearing the rule ID and pressing enter, the dashboards are updated but the list still shows only the previous filter result:

**Comment by chantal-kelm** [comment]
This bug has been fixed with the new dashboards.

**Attached is a video with tests below:**

https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/4505b48e-b994-49cb-94c7-d722b0c09caa

**Comment by asteriscos** [comment]
Reopening because the Security Events dashboard will not be implemented yet.
