### ISSUE TITLE
Inventory data report shows vulnerable packages of other agent when using shared hyperlink

### ISSUE THREAD

**Issue by ejdavids** [wazuh/wazuh-dashboard-plugins#6057]
If I share a direct link to the inventory data page of a specific agent from the address bar in the browser, and the recipient of this link navigates to this page and then uses the generate report feature, then the generated report shows vulnerable packages of the agent the recipient last viewed in the dashboard.

**To Reproduce**

User 1

1. Go to 'Agents' and select any agent
2. Click on 'Inventory data'
3. Share URL in browser address bar with user 2

User 2

1. Go to 'Agents' and select any agent (other than the agent user 1 selected)
2. Click on 'Vulnerabilities'
3. Open URL received from user 1
4. Click on 'Generate report'
5. Download and open report from Management/Reporting
6. See 'Vulnerable packages found (last 24 hours)' on first page of report

**Expected behavior**
Report should not include data of other agent

**OpenSearch Version**
? (Wazuh 4.5.2)

**Dashboards Version**
? (Wazuh 4.5.2)

**Plugins**
Out of the box single node deployment. No additional plugins.

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - Ubuntu 20.04.6 LTS
 - Chrome version 118.0.5993.71

**Additional context**

**Comment by asteriscos** [comment]
Hi @ejdavids, thanks for reporting this. There's a known issue with the current routing system which relies on angularJS. We are actively working on removing angularJS so this and other issues are solved.
