### ISSUE TITLE
Visualizations with different colors

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6095]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| X.Y.Z | xyzw | Chrome, Firefox, Safari, etc |

**Description**
Some visualizations use darker colors than the standard ones. This behavior happens at different "random" moments without apparent cause. 

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to any Dashboard

**Expected Result**
1. All visualizations should use the same colors

**Actual Result**
1. Some visualization use darker colors

**Screenshots**
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/385b91d3-9d4a-4bfa-92f2-25270fcb1e3c)

**Comment by gdiazlo** [comment]
Related to: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5422

**Comment by Desvelao** [comment]
The default colors of charts are defined by OpenSearch Dashboards by https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.10.0/src/plugins/charts/public/services/colors/mapped_colors.ts#L109-L112

**Comment by Desvelao** [comment]
The darker and lighter colors appear when the results of the visualization are more than 10, this causes the standard colors could not be used.

Reducing the aggregation size

In this screenshot, the colors assigned for the labels `3` and `Brute force` are the same ones.

**Comment by Desvelao** [comment]
Same colors for different labels in OSD 2.10.0 Dashboard app
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/34042064/e0fa7e88-b586-457f-bf4d-f6d2d42b84ed)

**Comment by chantal-kelm** [comment]
https://github.com/wazuh/wazuh-dashboard-plugins/issues/5838#issuecomment-1707163985

**Comment by Desvelao** [comment]
@asteriscos tried to use `order: middle-out` in https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.10.0/src/plugins/charts/public/services/colors/mapped_colors.ts#L109-L112, we got this result:

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/34042064/057076f1-d570-4f0f-870a-bb43f95d497e)

**Comment by Desvelao** [comment]
Video related to assigning colors to visualizations: https://youtu.be/U8by9Qikkhg?si=SerRIpbt8668h-Cj&amp;t=497

**Comment by yenienserrano** [comment]
A possible solution to the problem could be to overwrite the function that sets the colors of the graphs in our application with a few modifications.
Modifications:
- Adding the already mapped colors to the alreadyUsedColors variable.
- Change the data of the alreadyUsedColors variable to lowercase
- Change the values of the object passed to the euiPaletteColorBlind function. For this:
```javascript
 const colorPalette = euiPaletteColorBlind({
        rotations: Math.ceil(
          (keysToMap.length + alreadyUsedColors.length) / 10,
        ),
        direction: core.uiSettings.get('theme:darkMode') ? 'darker' : 'lighter',
      })
        .filter(color => !alreadyUsedColors.includes(color.toLowerCase()))
        .slice(0, keysToMap.length);
```
This causes, as labels are added to the visualizations, the color palette to expand and, depending on the theme, display light or dark colors in the graphics.

I share a patch with the changes: [paletteColor.txt](https://github.com/wazuh/wazuh-dashboard-plugins/files/13377401/paletteColor.txt)

<details><summary>Screenshots</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/9dcfe05e-3936-4ee3-bb12-f97b92c3087d)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/fac07ad6-bb15-4f58-89ae-9793dcf5c267)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/053d1ded-f7cf-46ff-8db9-04d7f2c81dc0)

</details>

**Comment by chantal-kelm** [comment]
I share a new patch that fixes the error in the colours of the visualisations:

[patch.txt](https://github.com/wazuh/wazuh-dashboard-plugins/files/13405163/patch.txt)

![image (9)](https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/ba548ff5-8832-4270-88e2-af05c2a973c0)
