### ISSUE TITLE
Feature request: Being able to rewrite 'agent.name' when processing syslog events (3rd party agents)

### ISSUE THREAD

**Issue by sl0w-parser** [wazuh/wazuh-dashboard-plugins#6131]
## Description
I would like to be able to rewrite 'agent.name' attribute. My usecase is multiple 3rd party devices (Cisco firewall, Synology NAS, ...) stored in separate log files, successfully read by Wazuh. From the Dashboard view, all these devices are marked as Wazuh (== events of the Wazuh server) and I would like them to be marked as the real device names in the Dashboard graphs. 

Editing the decoder doesn't solve the issue - if I decode some attribute as 'agent.name', it is then processed into the Wazuh manager as 'data.agent.name'. My request is to be able to rewrite 'agent.name'.

## Tasks
Add the possibility to rewrite the 'agent.name'. Possible places are:
- `<localfile>` configuration - that would perfectly fit my usecase
- decoder

**Comment by yenienserrano** [comment]
Hello @sl0w-parser, I understand that you want to overwrite the `agent.name` field because you get all the agents with the name `wazuh `right?

When you did the integrations, did you follow any specific guidelines?

The agents actually have another name, don't they? If so, do you get the name in another field?

**Comment by asteriscos** [comment]
Closed due to inactivity, feel free to open it again if you need to.

**Comment by sl0w-parser** [comment]
Hello Ian,
> I understand that you want to overwrite the [agent.name](http://agent.name/) field because you get all the agents with the name wazuh right

That's not correct. If I add the standard agent (single server > install SW agent > new agent pops in the Wazuh) everything works fine as expected. BUT I have several 3rd party devices, where I can't install the SW agent. I collect logs from them via Syslog sent to the Wazuh (to syslog service) and I would like to see them in the Wazuh dashboard as single agents.

Is it clear or should I add more comments?

**Comment by JohnGanem** [comment]
Hello,

We have the same problem, we are sending syslog events to Wazuh without installing an agent, so every log has the same agent.name (the server ip). Is there any way of modifying the agent.name like the author asked ? 

Thanks
