### ISSUE TITLE
The agents dashboard is displayed when using the Add agent button from plugin home

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#6175]
**Description**
The agents dashboard is displayed when using the Add agent button from the Modules directory section for a little period of time.

**Preconditions**
1. No registered agents

**Steps to reproduce**
1. Navigate to **Modules directory**
2. Click on **Add agent** button

**Expected Result**
The displayed view should be what we want to navigate to instead of this redirection behavior.

**Evidences**
https://github.com/wazuh/wazuh-dashboard-plugins/assets/34042064/69c6d5de-37f0-4a54-8dcd-e488bbd1c11c

**Comment by lucianogorza** [comment]
## Current behavior

The component `OverviewWelcome (plugins/wazuh/public/components/common/welcome/overview-welcome.js)`  has a button that is renderer only when there is no registered agents. The button has a href to the page `#/agents-preview`

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/b2dab1ce-58ca-4080-a749-43f81494e444)

**Comment by lucianogorza** [comment]
In a meeting with @asteriscos we decided to go for solution 2
