### ISSUE TITLE
Unexpected Canvas2D warning in HIPAA module

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh-dashboard-plugins#6182]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.7.1 | 40706 | Chrome |

**Description**
I was testing 4.7.1 [demo environment](https://github.com/wazuh/wazuh/issues/20458) and I was checking that there were no errors in the browser's developer console when browsing the App, when I entered to HIPAA module, I noted a Canvas2D warning: 

**Preconditions**
1. Demo environment

**Steps to reproduce**
1. Navigate to HIPAA module in Wazuh Dashboard

**Actual Result**
 ```console
Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
```

**Comment by asteriscos** [comment]
This error is from the OpenSearch platform. The warning suggests using a better method which is still not implemented in OpenSearch visualization. As soon as OpenSearch implements it, it should disappear.
