### ISSUE TITLE
Duplicated plots in Endpoints Summary

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-dashboard-plugins#6214]
| Wazuh | Revision  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 01 | Edge Version 119.0.2151.97 (Official build) (arm64) - macOS |

**Description**

When using the dashboard for the first time, the plots are duplicated.

**Preconditions**
1. Logout (if you already have a session active)
2. Login

**Steps to reproduce**
1. Go to Overview/Home
2. Navigate to Endpoints Summary

**Screenshots**

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/39094716/0375a621-3d98-4224-9c40-0368f32e453f)

https://github.com/wazuh/wazuh-dashboard-plugins/assets/39094716/1fe7fe11-27ae-4e33-a525-43ac5e7d04d8

**Comment by mauromalara** [comment]
I gave more details about the execution of this scenario and I recorded a video with more evidences and sent it to @gdiazlo

**Comment by gdiazlo** [comment]
This appears to come from an interaction between other platform plugins. We're redesigning this page in 
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6129

So we're closing this one in favor of what we already have on-going.
