### ISSUE TITLE
Notification points to a non-existing path

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-dashboard-plugins#6215]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 01 | Edge - macOS |

**Description**

The message that appears after generating a report is pointing to an invalid application path.

**Steps to reproduce**
1. Navigate to IT Hygiene
2. Select an agent
3. Go to Configuration option
4. Select Generate Report

**Expected result**

The path is: Menu > Indexer/dashboard management > Reporting

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/39094716/d757c828-fe7f-49d9-a08f-abe516d23a29)

**Screenshots**

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/39094716/1657f3c3-1fd2-4c76-ab1d-791143e7bdbe)

<br/>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/39094716/58d8d1c6-eaba-4870-b20f-ae7aa0273476)

**Comment by Tostti** [comment]
PR Successfully merged
