### ISSUE TITLE
The page freezes and shows a notable delay in the response of the elements

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-dashboard-plugins#6216]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 01 | Edge - macOS |

**Description**

I experienced a freeze page and a delay in the response of the elements (like buttons).

**Steps to reproduce**
1. Navigate to Threat Hunting
2. Search for any of these terms:
   - `*`
   - ` `
   - `st*`
   - `*ar*`
   - `*t`

**Expected Result**
1. The page should load the results without freezing or delaying the response

**Actual Result**
1. The page freezes and shows a notable delay in the response of the elements

**Screenshots**

> [!IMPORTANT]
> The following screenshot shows the delay

https://github.com/wazuh/wazuh-dashboard-plugins/assets/39094716/bccba0c3-84ac-45ba-890a-89c031c899f2

**Comment by AlexRuiz7** [comment]
Known issue

**Comment by gdiazlo** [comment]
We're working to modernize the Events tab of all the views in the application:

- #6120
