### ISSUE TITLE
Deprecation warning in the MomentJs library renders invalid date

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6220]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 01 | **Firefox** |

**Description**
There's a deprecation warning in the MomentJs library and the rendered date in the about page says `Invalid date`.
This only happens in Firefox browser.

Related to: https://github.com/wazuh/wazuh-dashboard-plugins/issues/6212

**Steps to reproduce**
1. Navigate to About page
2. See the Invalid date format

**Screenshots**
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/5fc16e69-f4f6-4189-aad9-9fc4a6fd8fde)

**Comment by asteriscos** [comment]
The About view controller was refactored into a React component and it seems the `installationDate` it's being formatted twice:

Commit with the change:
https://github.com/wazuh/wazuh-dashboard-plugins/pull/6093/files#diff-c900c5775274d404d9a38bbd1c01867050409635c93ef9491b8939e3512e3e02R59

React compoenent formatting the date:
https://github.com/wazuh/wazuh-dashboard-plugins/pull/6093/files#diff-55c9c5458437a38d5759eb9c5cb57421646530e95f7056858904690d5ad46388R30

AngularJS controller formatting the date:
https://github.com/wazuh/wazuh-dashboard-plugins/blob/cc0cfd9bfcd85752987015293c41ca3102e0f90a/plugins/main/public/controllers/settings/settings.js#L470

**Comment by mauromalara** [comment]
@asteriscos why did you duplicate the issue?

**Comment by asteriscos** [comment]
The invalid date issue has been reported in more than one view, like in this other issue:
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6207

We should analyze if the invalid date issue is related to the deprecation warning in each of the views with problems.
