### ISSUE TITLE
Release 4.7.2 - RC 1 - Wazuh UI regression testing

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6249]
The following issue aims to run manual tests for the current release candidate, report the results, and open new issues for any encountered errors.

## Wazuh UI tests information
|                                        |     |
|----------------------------------------|-----|
| **Main release candidate issue**       |   https://github.com/wazuh/wazuh/issues/21052  |
| **Version**                            |  4.7.2   |
| **Release candidate #**                |  RC1   |
| **Tag**                                |  v4.7.2-2.8.0-rc1   |
| **Previous UI regression tests issue** |   -  |

## Test report procedure

**TL;DR**
   1. The specified tests will be executed in every platform and version mentioned in this issue.
   1. Include evidence of each test performed.
   1. Report any problem or bug. Open a new issue for each of them and link them here.
   1. Justify skipped tests.

All test results must have one the following statuses: 
|                 |                                                                      |
|-----------------|----------------------------------------------------------------------|
| :black_circle:  | The test hasn't started yet.                                         |
| :green_circle:  | All checks passed.                                                   |
| :red_circle:    | There is at least one failed check.                                  |
| :yellow_circle: | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause.
It must be included in the `Problems` section of the current release candidate issue.

Any expected fail or skipped test must be justified with a reason. 
All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip, txt or images. 
This report can be used by the auditors to dig deeper into any possible failures and details.

## Test plan

1. Verify the app package installs and operates as expected.
2. #6202
3. #6190 
4. #6175 
5. #6203 
6. #6211 

## Conclusions

| Test | Chrome         | Firefox        | Safari         |
|------|----------------|----------------|----------------|
|  Verify the app package installs and operates as expected   | :green_circle: | :green_circle: | :white_circle: |
|  Standardize titles and subtitles in the register agent wizard #6202  | :green_circle: | :green_circle: | :white_circle: |
|  Add hostname and board_serial information in the agent inventory #6190  | :green_circle: | :green_circle: | :white_circle: |
|  The agents dashboard is displayed when using the Add agent button from plugin home #6175  | :green_circle: | :green_circle: | :white_circle: |
|  Change the endpoint to get Wazuh manager auth configuration #6203  | :green_circle: | :green_circle: | :white_circle: |
|  TypeError and Could not fetch data for this agent messages found after using the API Console #6211  | :green_circle: | :green_circle: | :white_circle: |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @wazuh/frontend 
- [ ] @davidjiglesias

**Comment by asteriscos** [comment]
# Test 
 
 ## Verify the app package installs and operates as expected. :green_circle: 
 
<details>
<summary>:green_circle: Chrome</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/7cef98e0-e197-4de1-a4b6-42636dcf81e4)



</details>
 
 <details>
<summary>:green_circle: Firefox</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/74e4d1ea-d160-4cec-a542-1bc475e09f16)



</details> 

 ## [Standardize titles and subtitles in the register agent wizard](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6202) :green_circle: 
  
<details>
<summary>:green_circle: Chrome</summary>

![screencapture-192-168-56-10-app-wazuh-2023-12-27-11_59_11](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/5049e808-e182-453c-9430-08a0d01aa987)
![screencapture-192-168-56-10-app-wazuh-2023-12-27-11_58_30](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/9b8beb70-0172-40cb-bb33-614a030d543b)
![screencapture-192-168-56-10-app-wazuh-2023-12-27-11_56_51](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/d225f926-c74e-4bae-86da-b767877b46ef)

</details>
 
 <details>
<summary>:green_circle: Firefox</summary>

![screencapture-192-168-56-10-app-wazuh-2023-12-27-11_56_51](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/a68ee3c5-6f03-4727-aa92-cac39ee3628c)
![screencapture-192-168-56-10-app-wazuh-2023-12-27-11_58_30](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/8929d261-7611-473d-b3dd-66f7cdc55dcb)
![screencapture-192-168-56-10-app-wazuh-2023-12-27-11_59_11](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/a5596b28-3512-4160-af09-e6c55ead9833)

</details> 



 ## [Add hostname and board_serial information in the agent inventory](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6190) :green_circle: 
 
<details>
<summary>:green_circle: Chrome</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/1b5b4b7e-b32e-4963-9fc9-5ca259ebde6c)


</details>
 
 <details>
<summary>:green_circle: Firefox</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/ad77de05-383b-4437-9a9a-f35fc3a913d3)


</details> 



 ## [The agent's dashboard is displayed when using the Add agent button from plugin home ](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6175) :green_circle: 
 
<details>
<summary>:green_circle: Chrome</summary>



</details>
 
 <details>
<summary>:green_circle: Firefox</summary>


</details> 



 ## [Change the endpoint to get Wazuh manager auth configuration](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6203) :green_circle: 
 
<details>
<summary>:green_circle: Chrome</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/47ec96c2-2be6-42dd-ac43-0c4dfe52906c)


</details>
 
 <details>
<summary>:green_circle: Firefox</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/2fa8cddc-f548-4283-a053-cfba58cd8150)


</details> 



 ## [TypeError and Could not fetch data for this agent messages found after using the API Console](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6211) :green_circle: 
 
<details>
<summary>:green_circle: Chrome</summary>


https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/148606d4-4fe1-43ad-8ed6-203cbc1a87b6



</details>
 
 <details>
<summary>:green_circle: Firefox</summary>


https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/52024bfc-bd1e-4c20-8794-ad52898b0160



</details>

**Comment by Tostti** [comment]
LGTM

**Comment by jbiset** [comment]
LGTM

**Comment by damarisg** [comment]
LGTM!
