### ISSUE TITLE
Problem with Wazuh installation using wazuh-install.sh script

### ISSUE THREAD

**Issue by WalidDevRes** [wazuh/wazuh-dashboard-plugins#6251]
Certainly! Here is the text without code blocks:

Issue Title:
Problem with Wazuh installation using wazuh-install.sh script

Issue Description:
I recently attempted to install Wazuh using the wazuh-install.sh script with the following command:

`curl -sO https://packages.wazuh.com/4.5/wazuh-... && chmod 744 wazuh-install.sh && bash ./wazuh-install.sh -a
`
However, I encountered an error during the installation process. The specific error is as follows:

`26/12/2023 17:55:16 ERROR: Could not load the changes.
`
Please provide assistance in resolving this issue.

**Comment by Shwet-Kamal-Singh** [comment]
Hi @WalidDevRes 

I've looked into the issue and found a command that might help.  Give this a try:

**curl -sO https://packages.wazuh.com/4.5/wazuh-install.sh && chmod 744 wazuh-install.sh && bash ./wazuh-install.sh -i -a**

**Comment by WalidDevRes** [comment]
Hi @Shwet-Kamal-Singh  I solve the problem it okay !!!
