### ISSUE TITLE
No Alpine package available for selection in the Deploy new agent section

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh-dashboard-plugins#6309]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 40802 | Chrome |

**Description**
I was performing the E2E UX tests for this issue: https://github.com/wazuh/wazuh/issues/21364. I have to install the Wazuh agent through Wazuh WUI (one-liner deploy) on an Alpine Linux machine. At the time of selecting the package to download and install, only the options for DEB and RPM packages are available but none of these are compatible with Alpine.
 

**Steps to reproduce**
1. Navigate to Server management -> Endpoints Summary.
2. Click on Deploy new agent.

**Expected Result**
1. Alpine package to select.

**Actual Result**
1. Only DEB and RPM packages availables.

**Screenshots**
![2024-01-12_13-30](https://github.com/wazuh/wazuh-dashboard-plugins/assets/101177239/f7a067ff-42b0-4b44-9a4f-43c8e149b536)

**Comment by gdiazlo** [comment]
We changed this design in 4.6.0 to simplify the UI. To deploy other os / architectures, we should follow the documentation, as stated in the call-out.
