### ISSUE TITLE
MITRE ATT&CK dashboard cutout graphs

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-dashboard-plugins#6313]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | Alpha 2 | Firefox |

**Description**
During the test performed in https://github.com/wazuh/wazuh/issues/21365, when examining the dashboard graphs, it could be seen that they are cut off on the left, not being able to see `Count` completely, and the `Alerts evolution over time` graph is cut off at the top, preventing the events from being clearly seen.

**Steps to reproduce**
1. Navigate to MITRE ATT&CK module
2. Click on Dashboard
3. Check graphs

**Expected Result**
The graphs should appear in their entirety.

**Actual Result**
The graphs are trimmed

**Screenshots**
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/80041853/ab90e622-80c7-4077-aa8b-c2982d2b3c93)

**Comment by gdiazlo** [comment]
I could not reproduce it with Firefox 122.0b6-b9. Could you share with us more details? like the Firefox version, the installed plugins, screen/window size, zoom level, etc?

**Comment by gdiazlo** [comment]
We've been able to reproduce it with Firefox on ubuntu. FIrefox on macOs and Windows does not exhibit this problem.
