### ISSUE TITLE
The vulnerability detector event filter can sometimes be removed, displaying confusing information

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-dashboard-plugins#6316]
| Wazuh | Elastic | Rev  | 
| ----- | ------- | ---- | 
| 4.8.0-alpha2   | 7.x     | 1| 

| Browser |
| ------- |
| Firefox|

**Description**
Testing [E2E UX tests - Demo environment 4.8.0-alpha2 ](https://github.com/wazuh/wazuh/issues/21356)

In Vulnerability Detector/Events

At times, the filters related to Vulnerability Detector can be removed, and at times they cannot. (Check de X, which is not related to the position of the pointer over the button)
![image](https://github.com/wazuh/wazuh/assets/125690423/dca12536-5f5b-4f91-bfbc-18968075958f)
![image](https://github.com/wazuh/wazuh/assets/125690423/8b8e69b3-bc4a-440f-8231-7d3abfd33478)

On the other hand, this can be harmful because if the user deletes the filter, it brings in information that does not belong to VD and can confusing to the user. The user may not know which filter to use and find themselves in a situation like this:
![image](https://github.com/wazuh/wazuh/assets/125690423/b5dc632a-5395-4d53-a9d2-2ec08b09dbc5)
![image](https://github.com/wazuh/wazuh/assets/125690423/5e11b78a-45fb-4700-be53-ab14be235544)
where information not relevant to the module is shown. (The image shows the lack of data since, as these are events not related to the module, there is an absence of parameters.)

Removing the filter and trying to re add it manually, the filter was absent in between the options:
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/125690423/6994a92d-f217-4445-b8bf-032cead2ba46)

**Preconditions**
- Installation of wazuh 4.8.0-alpha2

**Steps to reproduce**
Click on the Vulnerability detector and go to events.
The option to remove was available randomly.
After removing the filter, the filter was back after re-opening the VD module in a new tag in the browser. However, it was not reappearing re-logging the user.

**Comment by jbiset** [comment]
# Research

## Filter Management.

A filter can exist in various "states," determining whether it can be removed, lost when changing screens, or if the filter condition should be negated. OpenSearch Dashboard manages the recognition of these "states" during rendering through the data-test-subj attribute value, taking the following into consideration:

```javascript
const dataTestSubjNegated = filter.meta.negate ? 'filter-negated' : '';
const dataTestSubjDisabled = `filter-${isDisabled(labelConfig) ? 'disabled' : 'enabled'}`;
const dataTestSubjPinned = `filter-${isFilterPinned(filter) ? 'pinned' : 'unpinned'}`;
```

The modules-helper, by editing the above values, enables or disables implicit filters, hides or shows the close button, and allows or disallows actions on the filter.

Files involved in updating filter states:

- plugins/main/public/services/common-data.js
- plugins/main/public/kibana-integrations/kibana-discover.js
- plugins/main/public/components/common/modules/modules-helper.js
