### ISSUE TITLE
Error: Error getting API entries

### ISSUE THREAD

**Issue by williambatistaa17** [wazuh/wazuh-dashboard-plugins#6317]
| Wazuh | v4.7.2 | Chrome / Edge

**Description**
I install Wazuh v4.7.2 in  Ubuntu Server 22.04.3 LTS in 12/26/23.
In last week the system crashed and I tried differents solutions and and it didn't work.

**PROBLEM**
Error: 2001 - Unexpected end of JSON input
    at _callee$ (https://10.31.10.33/47202/bundles/plugin/wazuh/wazuh.plugin.js:1:192930)
    at tryCatch (https://10.31.10.33/47202/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:786910)
    at Generator.invoke [as _invoke] (https://10.31.10.33/47202/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:790926)
    at Generator.throw (https://10.31.10.33/47202/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:788105)
    at asyncGeneratorStep (https://10.31.10.33/47202/bundles/plugin/wazuh/wazuh.plugin.js:1:188368)
    at _throw (https://10.31.10.33/47202/bundles/plugin/wazuh/wazuh.plugin.js:1:188765)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Check Wazuh API connection**
INFO: Current API id [default]
INFO: Checking current API id [default]...
INFO: Current API id [default] has some problem: 3002 - Request failed with status code 403
INFO: Getting API hosts...
ERROR: Error connecting to API: Error: 2001 - Unexpected end of JSON input
INFO: Removed [navigate] cookie
ERROR: Error connecting to API: Error: 2001 - Unexpected end of JSON input


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Check alerts index pattern**
INFO: Index pattern id in cookie: yes [wazuh-alerts-*]
INFO: Getting list of valid index patterns...
INFO: Valid index patterns found: 1
INFO: Found default index pattern with title [wazuh-alerts-*]: yes
INFO: Checking the app default pattern exists: id [wazuh-alerts-*]...
INFO: Default pattern with id [wazuh-alerts-*] exists: yes
ACTION: Default pattern id [wazuh-alerts-*] set as default index pattern
INFO: Checking the index pattern id [wazuh-alerts-*] exists...
INFO: Index pattern id exists [wazuh-alerts-*]: yes
INFO: Index pattern id in cookie: yes [wazuh-alerts-*]
INFO: Checking if the index pattern id [wazuh-alerts-*] exists...
INFO: Index pattern id [wazuh-alerts-*] found: yes title [wazuh-alerts-*]
INFO: Checking if exists a template compatible with the index pattern title [wazuh-alerts-*]
INFO: Template found for the selected index-pattern title [wazuh-alerts-*]: yes
INFO: Index pattern id in cookie: [wazuh-alerts-*]
INFO: Getting index pattern data [wazuh-alerts-*]...
INFO: Index pattern data found: [yes]
INFO: Refreshing index pattern fields: title [wazuh-alerts-*], id [wazuh-alerts-*]...
ACTION: Refreshed index pattern fields: title [wazuh-alerts-*], id [wazuh-alerts-*]
INFO: Getting settings...
INFO: Check Wazuh dashboard setting [timeline:max_buckets]: 200000
INFO: App setting [timeline:max_buckets]: 200000
INFO: Settings mismatch [timeline:max_buckets]: no
INFO: Getting settings...
INFO: Check Wazuh dashboard setting [metaFields]: ["_source","_index"]
INFO: App setting [metaFields]: ["_source","_index"]
INFO: Settings mismatch [metaFields]: no
INFO: Getting settings...
INFO: Check Wazuh dashboard setting [timepicker:timeDefaults]: {"from":"now-24h","to":"now"}
INFO: App setting [timepicker:timeDefaults]: "{\"from\":\"now-24h\",\"to\":\"now\"}"
INFO: Settings mismatch [timepicker:timeDefaults]: no

**Screenshots**
![tela 1](https://github.com/wazuh/wazuh-dashboard-plugins/assets/156676178/b4c82d6d-8c82-467d-ab90-40506b2af10e)

**Additional context**
Before last week, this system open normally

**Comment by yenienserrano** [comment]
Hi @williambatistaa17 , I understand that you can't connect to the API, can you tell me if you have made any new configuration recently? Can you show me the wazuh.yml configuration to see if the problem is there (always hiding the passwords)?
