### ISSUE TITLE
Recently viewed button always shows empty options in the sidebar

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-dashboard-plugins#6318]
| Wazuh | Elastic | Rev  | 
| ----- | ------- | ---- | 
| 4.8.0-alpha2   | 7.x     | 1| 

| Browser |
| ------- |
| Firefox|

**Description**
Testing [E2E UX tests - Demo environment 4.8.0-alpha2 ](https://github.com/wazuh/wazuh/issues/21356)

Recently viewed button always shows empty options

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/125690423/65ef934f-a505-4be8-b2b7-7b326cd130bb)

**Preconditions**
- Installation of wazuh 4.8.0-alpha2

**Steps to reproduce**
Click on the hamburger button on the top left side
Click on Recently viewed (after some navigation for different modules/pages)

**Comment by asteriscos** [comment]
This known issue. We will address it in the future.

**Comment by JuanGarriuz** [comment]
"Recently viewed" is a Kibana feature, which is being managed separately from the Wazuh plugins. Its function is exclusively provided in the OpenSearch dashboards.

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/020401b0-c270-4824-a797-526cf1a1f525)
