### ISSUE TITLE
Remove scroll from vulnerabilities inventory table

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6324]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 02 | Chrome, Firefox, Safari, etc |

**Description**
Sometimes the Vulnerabilities Inventory table adds a scroll that has no use. This happens when we search for a value in the search bar that returns just 1 value in the table and then we change the search to return some other results.

**Preconditions**
1. Have alerts in the vulnerabilities dashboard

**Steps to reproduce**
1. Navigate to Vulnerabilities / Inventory
2. Click on the search bar input
3. Search for a value that returns just 1 result
4. Search for another value that returns a few results

**Expected Result**
1. It shouldn't render a scroll in the table

**Actual Result**
1. Renders a scrollbar

https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/0f8daa88-2bda-4a79-b491-037ececa3f63

**Screenshots**

**Comment by yenienserrano** [comment]
issue is created in opensearch oui because it comes from the library the problem

- https://github.com/opensearch-project/oui/issues/1211
