### ISSUE TITLE
FIM module - Index not found message

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh-dashboard-plugins#6325]
## Description

In the FIM module, when an index is not found, the dashboard loads but without data, the same happens in the inventory and events tab of the same module.

### What we want:

We want that if the index is not found the dashboard does not load and displays an index not found message, the same behaviour we want to happen in the inventory and events tab of the same module.

## Tasks
The steps that have to be completed in order to close the issue.

- [x] Reuse components from other application modules to achieve the desired behavior.

## Additional information
Add here any additional information relevant to the issue or that will help to close it: chunks of code, logs, additional error messages, related issues and so on.

**Comment by asteriscos** [comment]
This change is postponed.
