### ISSUE TITLE
Feature request: Add Wodles Credentials through the WUI

### ISSUE THREAD

**Issue by Zapatannicolas** [wazuh/wazuh-dashboard-plugins#6331]
## Description

Hi team!

I would like to propose a feature enhancement to the Wazuh UI, specifically for the Wazuh S3 Wodle. Currently, the credentials configuration for these modules is done manually, and I believe it would greatly benefit users if they could configure these credentials directly from the UI.

**Comment by asteriscos** [comment]
Thanks a lot for the suggestion. We will consider this for future releases.
