### ISSUE TITLE
Split index/dashboard management menu

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard-plugins#6357]
## Description

We want to separate the index/dashboard management menu into indexer management and dashboard management.

Dashboard management
- [Dashboards Management]
- [Reporting]
- [Server APIs]
- [App Settings]
- [App Logs]
- [About]

Indexer management
- [Index Management]
- [Snapshot Management]
- [Security]
- [Sample Data]
- [Dev Tools]

The current implementation is implemented like:

<img width="317" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/2181918/319c9c64-5530-45ec-bf27-741fe0b77f5c">

## Tasks
The steps that have to be completed in order to close the issue.

- [x] Split the menu as described
- [x] Update the relevant documentation sections

**Comment by Desvelao** [comment]
# Analysis

The proposition requires:

- Create the proposed categories
> Create the new ones categories (maybe this could be the recommended way)
> Create a new one and rename the existingPues habría que definir para cada plugin la categoría a la que pertenece.

Affected repositories:
- `wazuh-dashboard-plugins`
- `wazuh-packages`

**Comment by lucianogorza** [comment]
I didn´t find documentation to update
