### ISSUE TITLE
Update usage of refactored API endpoints

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-dashboard-plugins#6381]
## Description

We have decided to refactor the following endpoints as part of the fix necessary for https://github.com/wazuh/wazuh/issues/20851:
- [GET /groups/{group_id}/files/{file_name}/json](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_group_file_json)
- [GET /groups/{group_id}/files/{file_name}/xml ](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_group_file_xml)

Both endpoints have been replaced by this one:
- **GET /groups/{group_id}/files/{file_name}**

The reason is that they did not work correctly. For example, `GET /groups/{group_id}/files/{file_name}/xml` did not transform files to XML, it simply included `application/xml` as a content-type header. Therefore, it only worked correctly when trying to get `agent.conf` files.

On the other hand, when using `GET /groups/{group_id}/files/{file_name}/json` to obtain, for example, the `merged.mg` file, the content was incorrect since there were some parts skipped.

The new **GET /groups/{group_id}/files/{file_name}** endpoint always returns `JSON`. It also includes a new parameter `raw` to obtain the content of the file as is. 

## Tasks
The steps that have to be completed in order to close the issue.

- [ ] Search usages of `GET /groups/{group_id}/files/{file_name}/json` and `GET /groups/{group_id}/files/{file_name}/xml` in the dashboard.
- [ ] Replace those usages with `GET /groups/{group_id}/files/{file_name}` or `GET /groups/{group_id}/files/{file_name}?raw=true`

## Additional information

Example outputs.

> GET /groups/default/files/agent.conf

```JSON
{
  "data": {
    "total_affected_items": 1,
    "affected_items": [
      {
        "filters": {},
        "config": {}
      }
    ]
  },
  "error": 0
}
```

> GET /groups/default/files/agent.conf?raw=true

```XML
<agent_config>
  <!-- Shared agent configuration here -->
</agent_config>
```

**Comment by Tostti** [comment]
PR successfully merged
