### ISSUE TITLE
Release 4.8.0 - Beta 1 - Wazuh UI regression testing

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh-dashboard-plugins#6386]
The following issue aims to run manual tests for the current release candidate, report the results, and open new issues for any encountered errors.

## Wazuh UI tests information
|                                        |     |
|----------------------------------------|-----|
| **Main release candidate issue**       |   https://github.com/wazuh/wazuh/issues/21774  |
| **Version**                            |  4.8.0   |
| **Release candidate #**                |  Beta 1   |
| **Tag**                                |  v4.8.0-2.10.0-beta1   |
| **Previous UI regression tests issue** |  https://github.com/wazuh/wazuh-dashboard-plugins/issues/6307   |

## Test report procedure

**TL;DR**
   1. The specified tests will be executed in every platform and version mentioned in this issue.
   1. Include evidence of each test performed.
   1. Report any problem or bug. Open a new issue for each of them and link them here.
   1. Justify skipped tests.

All test results must have one the following statuses: 
|                 |                                                                      |
|-----------------|----------------------------------------------------------------------|
| :white_circle:  | Doesn't apply |
| :black_circle:  | The test hasn't started yet.                                         |
| :green_circle:  | All checks passed.                                                   |
| :red_circle:    | There is at least one failed check.                                  |
| :yellow_circle: | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause.
It must be included in the `Problems` section of the current release candidate issue.

Any expected fail or skipped test must be justified with a reason. 
All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip, txt or images. 
This report can be used by the auditors to dig deeper into any possible failures and details.

## Test template

| Test | Chrome         | Firefox        | Safari         |
|------|----------------|----------------|----------------|
| -    | :black_circle: | :black_circle: | :white_circle: |

## Test plan

1. Verify the app package installs and operates as expected.
2. [Failure of script during Mac OS Agent deployment](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6294)
3. [Incorrect abbreviation for `Fully Qualified Domain Name`](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6310)
4. [The `Server address` field in the `Deploy new agent section` does not accept hostnames as indicated in the documentation](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6311)
5. [MITRE ATT&CK dashboard cutout graphs](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6313)
6. [Disable the discover legacy callout warning by default](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6314)
7. [The vulnerability detector event filter can sometimes be removed, displaying confusing information](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6316)
8. [Disable by default the vulnerabilities health-check](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6319)
9. [Maximized visualizations don't display properly in vulnerabilities dashboard](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6322)
10. [Vulnerabilities inventory tab table doesn't maximize properly](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6323)
11. [Remove scroll from vulnerabilities inventory table](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6324)
12. [Vulnerability detail truncated text in big fields](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6332)
13. [Server stat "Archives queue usage" is picking the wrong value](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6340)
14. [Statistics error when cluster mode is disabled](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6343)
15. [Remove `WAZUH_REGISTRATION_SERVER` from Windows deploy cmd](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6348)
16. [Wazuh's favicon does not appear in safari](https://github.com/wazuh/wazuh-packages/issues/2788)
17. [Add agent name and id  in vulnerability inventory as a default field](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6350)
18. [Refactor "run as" render in server APIs](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6351)
19. [Refactor top N tables in vulnerabilities dashboard](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6353)
20. [Split index/dashboard management menu](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6357)
21. [Add tooltip to most active agent label](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6358)
22. [Add pinned agent to vulnerability section](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6359)
23. [Remove IT hygiene section](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6360)
24. [Remove compilation date from dashboard](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6365)
25. [Refactor the home section top kpi](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6367)
26. [Remove duplicated links from help menu](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6368)
27. [Change API configuration title](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6369)
28. [Support new vulnerability configuration block](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6370)

## Test

| Test                                   | Chrome      | Firefox     | Safari      |
|----------------------------------------|-------------|-------------|-------------|
| Verify the app package installs and operates as expected | 🟢 | 🟢 | :white_circle: |
| Failure of script during Mac OS Agent deployment | 🟢  | 🟢 | :white_circle: |
| Incorrect abbreviation for `Fully Qualified Domain Name` | 🟢 | 🟢 | :white_circle: |
| The `Server address` field in the `Deploy new agent section` does not accept hostnames as indicated in the documentation | 🟢 | 🟢 | :white_circle: |
| MITRE ATT&CK dashboard cutout graphs | 🟢 | 🟢 | :white_circle: |
| Disable the discover legacy callout warning by default | 🟢 | 🟢 | :white_circle: |
| The vulnerability detector event filter can sometimes be removed, displaying confusing information | 🟢 | 🟢 | :white_circle: |
| Disable by default the vulnerabilities health-check | 🟢 | 🟢 | :white_circle: |
| Maximized visualizations don't display properly in vulnerabilities dashboard | 🟢 | 🟢 | :white_circle: |
| Vulnerabilities inventory tab table doesn't maximize properly | 🟢 | 🟢 | :white_circle: |
| Remove scroll from vulnerabilities inventory table | 🟢 | 🟢 | :white_circle: |
| Vulnerability detail truncated text in big fields | 🟢 | 🟢 | :white_circle: |
| Server stat "Archives queue usage" is picking the wrong value | 🟢 | 🟢 | :white_circle: |
| Statistics error when cluster mode is disabled | 🟢 | 🟢 | :white_circle: |
| Remove `WAZUH_REGISTRATION_SERVER` from Windows deploy cmd | 🟢 | 🟢 | :white_circle: |
| Wazuh's favicon does not appear in safari | 🟢 | 🟢 | 🟢 |
| Add agent name and id  in vulnerability inventory as a default field | 🟢 | 🟢 | :white_circle: |
| Refactor "run as" render in server APIs | 🟢 | 🟢 | :white_circle: |
| Refactor top N tables in vulnerabilities dashboard | 🟢 | 🟢 | :white_circle: |
| Split index/dashboard management menu | 🔴  | 🔴 | :white_circle: |
| Add tooltip to most active agent label | 🟢 | 🟢 | :white_circle: |
| Add pinned agent to vulnerability section | 🟢 | 🟢 | :white_circle: |
| Remove IT hygiene section | 🟢 | 🟢 | :white_circle: |
| Remove compilation date from dashboard | 🟢 | 🟢 | :white_circle: |
| Refactor the home section top kpi | 🟢 | 🟢 | :white_circle: |
| Remove duplicated links from help menu | 🟢 | 🟢 | :white_circle: |
| Change API configuration title | 🟢 | 🟢 | :white_circle: |
| Support new vulnerability configuration block | 🟢 | 🟢 | :white_circle: | 
 
## Conclusions

All tests have been executed and the results can be seen above.
We found that the issue [Split index/dashboard management menu](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6357) is not implemented in the app because this [Pull Request](https://github.com/wazuh/wazuh-packages/pull/2795) was merged after this [Tag](https://github.com/wazuh/wazuh-packages/releases/tag/v4.8.0-beta1) was created.
We only tested in Safari the issue [Wazuh's favicon does not appear in safari](https://github.com/wazuh/wazuh-packages/issues/2788) because we needed a third-party device to do it.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted to close this issue.

- [x] @asteriscos

**Comment by lucianogorza** [comment]
## Test

| Test                                   | Chrome      | Firefox     | Safari      |
|----------------------------------------|-------------|-------------|-------------|
| Verify the app package installs and operates as expected | 🟢 | 🟢 | :black_circle: |
| Failure of script during Mac OS Agent deployment | :black_circle: | :black_circle: | :black_circle: |
| Incorrect abbreviation for `Fully Qualified Domain Name` | :black_circle: | :black_circle: | :black_circle: |
| The `Server address` field in the `Deploy new agent section` does not accept hostnames as indicated in the documentation | :black_circle: | :black_circle: | :black_circle: |
| MITRE ATT&CK dashboard cutout graphs | :black_circle: | :black_circle: | :black_circle: |
| Disable the discover legacy callout warning by default | :black_circle: | :black_circle: | :black_circle: |
| The vulnerability detector event filter can sometimes be removed, displaying confusing information | :black_circle: | :black_circle: | :black_circle: |
| Disable by default the vulnerabilities health-check | :black_circle: | :black_circle: | :black_circle: |
| Maximized visualizations don't display properly in vulnerabilities dashboard | :black_circle: | :black_circle: | :black_circle: |
| Vulnerabilities inventory tab table doesn't maximize properly | :black_circle: | :black_circle: | :black_circle: |
| Remove scroll from vulnerabilities inventory table | :black_circle: | :black_circle: | :black_circle: |
| Vulnerability detail truncated text in big fields | :black_circle: | :black_circle: | :black_circle: |
| Wazuh dashboards for Splunk integration do not display correctly using dark mode | :black_circle: | :black_circle: | :black_circle: |
| Server stat "Archives queue usage" is picking the wrong value | :black_circle: | :black_circle: | :black_circle: |
| Statistics error when cluster mode is disabled | :black_circle: | :black_circle: | :black_circle: |
| Remove `WAZUH_REGISTRATION_SERVER` from Windows deploy cmd | :black_circle: | :black_circle: | :black_circle: |
| Wazuh's favicon does not appear in safari | :black_circle: | :black_circle: | :black_circle: |
| Add agent name and id  in vulnerability inventory as a default field | :black_circle: | :black_circle: | :black_circle: |
| Refactor "run as" render in server APIs | :black_circle: | :black_circle: | :black_circle: |
| Refactor top N tables in vulnerabilities dashboard | :black_circle: | :black_circle: | :black_circle: |
| Split index/dashboard management menu | :black_circle: | :black_circle: | :black_circle: |
| Add tooltip to most active agent label | :black_circle: | :black_circle: | :black_circle: |
| Add pinned agent to vulnerability section | :black_circle: | :black_circle: | :black_circle: |
| Remove IT hygiene section | :black_circle: | :black_circle: | :black_circle: |
| Remove compilation date from dashboard | :black_circle: | :black_circle: | :black_circle: |
| Refactor the home section top kpi | :black_circle: | :black_circle: | :black_circle: |
| Remove duplicated links from help menu | :black_circle: | :black_circle: | :black_circle: |
| Change API configuration title | :black_circle: | :black_circle: | :black_circle: |
| Support new vulnerability configuration block | :black_circle: | :black_circle: | :black_circle: |

## Verify the app package installs and operates as expected.  
  
<details>
<summary>  🟢  Chrome</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/50d1de0c-909a-4c0d-b4b6-9196278af9be)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/d8fadc28-efb6-4dd6-b6b8-8c05d2a8d8d5)

</details>
 
 <details>
<summary>  🟢  Firefox</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/582d8b7e-7a8e-437a-950b-27a991902982)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/7feeace0-d646-4c4e-b4a1-a1c4296b6cc5)

</details>

**Comment by asteriscos** [comment]
LGTM :green_circle:

**Comment by davidjiglesias** [comment]
LGTM
