### ISSUE TITLE
Check the GET /groups endpoint paginates

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6388]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.1 | 00 | Chrome, Firefox, Safari, etc |

**Description**
There's been a fix in the endpoint `GET /groups` and we need to ensure the current Wazuh Dashboard implementations work properly. Previous to this fix, the endpoint only returned the first 500 results; since the pagination fix it should allow iterating throw different pages of the group requests.

There's a known issue that persists and will be fixed in 4.9.0. Even though the results are paginated, the filters are applied only to the selected page.

Task:

- [x] Test all implementations of the `GET /groups` requests

Source reference issue: 
- https://github.com/wazuh/wazuh/issues/20942

**Comment by JuanGarriuz** [comment]
From the 500th group onwards, the request does not take all the values it should.

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/cda565f9-9aa3-47f9-9b12-2658db04fa7d)
