### ISSUE TITLE
Health-check vulnerabilities index-pattern validation should be removed

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6395]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 03 | Chrome, Firefox, Safari, etc |

**Description**
Currently, the health-check vulnerabilities index-pattern validation is disabled by default, but Wazuh manager has the vulnerabilities modules enabled by default, except when it's an upgraded installation. Therefore we need to contemplate several possible states in Wazuh Dashboard to ensure the vulnerabilities module can work properly.

These verifications will be made whenever a user accesses the vulnerabilities module, hence we need to make all the necessary checks in the vulnerabilities dashboard and inventory

**Expected Result**
1. The vulnerabilities index-pattern verification should be removed from the health-check
2. The vulnerabilities index-pattern verification configuration should be removed from the app settings
3. The proper validations will be made in the vulnerabilities module in this related issue
  - https://github.com/wazuh/wazuh-dashboard-plugins/issues/6394

**Screenshots**

![screencapture-localhost-5601-app-app-settings-2024-02-08-16_30_24](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/1ade552e-388a-4f1e-9f17-6c9325ad4883)

![Screenshot from 2024-02-08 16-30-57](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/8dd7871c-1480-4b62-b4d8-523d8eb0b000)

**Comment by Desvelao** [comment]
# Changes

- The check related to the vulnerabily pattern was removed from the health check
- The plugin setting `checks.vulnerabilities.pattern` was removed
