### ISSUE TITLE
Install dashboard from github source

### ISSUE THREAD

**Issue by ptlearnertp** [wazuh/wazuh-dashboard-plugins#6403]
HI there

i would like to install the dashboard from the github source, any help that how may i do it? 
as i see the make file is not correct and also to install it using npm, there is no webpack conf

**Comment by JuanGarriuz** [comment]
Hello @ptlearnertp.

### If you want to compile a version prior to 4.9:

1. Go to [wazuh-packages GitHub repository](https://github.com/wazuh/wazuh-packages) (in the branch of the required version).
2. In `wazuhapp/opensearch-dashboards`, run `generate_wazuh_app.sh`. This creates the plugins 

> if you want to modify something in the plugin, you need to modify this script to fetch the data from another place instead of the Wazuh repository

3. Go to `stack/dashboard/<package type>` and run `build_package.sh` with the required parameters (`main-app`, `updates-app`, and `core-app` are obtained with the previous script). It only takes one URL, but it can be a local file 

> e.g., `file:///home/user/file`

### If you want to compile a version equal to or greater than 4.9:

1. Clone [wazuh-dashboard GitHub repository](https://github.com/wazuh/wazuh-dashboard)

> in the corresponding branch


2. Clone [wazuh-dashboard-plugins GitHub repository](https://github.com/wazuh/wazuh-dashboard-plugins) 

> in the corresponding branch


3. In the `plugins` folder, copy all the folders from `wazuh-dashboard-plugins` to the `plugins` folder of the previously cloned `wazuh-dashboard` repository.
4. In the `plugins` folder of `wazuh-dashboard`, also clone [wazuh-security-dashboards-plugin GitHub repository](https://github.com/wazuh/wazuh-security-dashboards-plugin) (in the corresponding branch).
5. At the root of `wazuh-dashboard`, run `yarn osd bootstrap` (it may show errors).
6. Inside `plugins/main`, run `yarn build`. When asked for the version of Opensearch Dashboards, input the one found in `package.json` under `pluginplatform/version`.
7. Do the same for `wazuh-core`, `wazuh-check-updates`, and `wazuh-security-dashboards-plugin` (this generates a zip inside the `build` folder of each plugin).
8. Generate a zip containing the three zips of `wazuh-core`, `wazuh-check-updates`, and `main`.
9. Generate a zip containing the zip of `wazuh-security-dashboards-plugin`.
10. Delete everything in the `plugins` folder, then at the root, run `yarn osd bootstrap` and `yarn build --release --skip-os-packages --linux`. This creates a `tar.gz` inside the `target` folder.
11. In `dev-tools/build-packages/`, run `build-packages.sh` with the required parameters:
    - `app` is the zip with the three plugins (URL format; if local, it is `file:///home/user/etc...`).
    - `base` is the `tar.gz` generated in the last step.
    - `security` is the zip containing the security plugin.

For all these cases, you need to have Docker installed and an internet connection.
