### ISSUE TITLE
Improve MITRE ATT&CK Framework tab error handling

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh-dashboard-plugins#6404]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| v4.8.0-Beta1 | Dashboard | MITRE ATT&CK Framework tab| Ubuntu 20.04 |

### Description
When the indexer server is not working, the MITRE ATT&CK framework tab shows pop-up errors when the user presses the refresh button. Still, it doesn't alert the user that the indexer service is not working as expected.

The details of the screen and why this feature is requested can be found in this [issue](https://github.com/wazuh/wazuh/issues/21767).

**Comment by AlexRuiz7** [comment]
MITRE framework details are fetched from the API, not from Indexer
