### ISSUE TITLE
Rename package.path from Most vulnerable endpoints Vulnerability Detection visualization

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-dashboard-plugins#6409]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | Beta 1 | Firefox |

**Description**

Confusing package.path label. I suggest using `agent.id` instead.

**Preconditions**
1. Deploy an all-in-one
2. Enable vulnerability detection
3. Enable vulnerability indexes
4. Wait until scan is over
5. Check the `Most vulnerable endpoints` report in the Vulnerability Section > Dashboard section

**Expected Result**
packages.path should be renamed to agent.id

**Screenshots**

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/11089305/fabac63a-13e3-43fa-9978-e3b915e1c8c6)

**Comment by Desvelao** [comment]
The label of the visualization will be modified on https://github.com/wazuh/wazuh-dashboard-plugins/issues/6416.

I will close the issue.
