### ISSUE TITLE
Last 24 hours alerts link redirect to Discover instead of Security alerts menu

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-dashboard-plugins#6414]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0| beta1 | Firefox |

**Description**
Currently, the link for the last 24 hours alerts redirects users to the Discover menu instead of the Security alerts section, where they can access more comprehensive information. To enhance user experience and ensure they have access to the most relevant information, I recommend updating the link to direct users to the Security alerts section instead

**Preconditions**
1. Deploy an All-In-One

**Steps to reproduce**
1. Navigate to `Last 24 hours alerts` link
2. Discover menu is open

**Screenshots**
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/11089305/4cbebac4-ce5e-47c6-b808-fb3f3dd12b41)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/11089305/a7151f0c-f00d-4c46-8463-890eda412fac)

**Comment by Desvelao** [comment]
Hi @Rebits, the redirection to the `Discover` application is intentional according to the issue: https://github.com/wazuh/wazuh-dashboard-plugins/issues/6367

I will close the issue.
