### ISSUE TITLE
Change most vulnerable endpoints label to endpoint name

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6416]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 03 | - |

**Description**
The "Most vulnerable endpoints" visualization is currently showing the endpoint ID and it renders the label as _"package.path"_. Both things make the visualization very confusing and misleading. To fix this we have to change the label to **_Endpoint name_** and show the field `agent.name`

**Expected Result**
1. The "package.path" of the "Most vulnerable endpoints" visualization must be changed to "Endpoint name"
2. This visualization should render the field `agent.name` (instead of the _agent.id_)

**Screenshots**

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/7a517a48-695b-4234-ac0b-91daf0c7c5d6)

**Comment by Desvelao** [comment]
According to this issue that requested to fix the label of `package.path. Because of the value to display in the vertical axis will be changed to `agent.id`, we should display an appropriate label.

**Comment by Tostti** [comment]
PR successfully merged
