### ISSUE TITLE
The alerts related to Wazuh servers are not excluded on the Dashboard and Events tabs when the hideManagerAlerts setting is enabled

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#6430]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| - | - | - |

**Description**
The alerts related to Wazuh servers are not excluded on the Events (and sometimes on the Dashboard) tab when the `hideManagerAlerts` setting is enabled.

Related findings: https://github.com/wazuh/wazuh-dashboard-plugins/issues/6420#issuecomment-1952129793

**Preconditions**
1. Enable the `hideManagerAlerts` setting of the plugin.
2. Ensure there are data related to Wazuh servers (`agent.id` is `000`)

**Steps to reproduce**
1. Navigate to any module > `Events`
2. Add a filter `agent.id` `is` `000` and see if there are data.

**Expected Result**
1. When the `hideManagerAlerts` is enabled, the `Events` tab should not display data about the Wazuh server.

**Evidences**
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/34042064/a4159de1-2b75-4823-8f4b-f22729aa95b4)

**Comment by Desvelao** [comment]
# Research

It seems some visualizations on the Dashboards tabs could not exclude the data related to Wazuh servers when the `hideManagerAlerts` are enabled. In the following screenshots, the `Total` count is 0 menawhile the visualizations display some data.
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/34042064/bdafc20e-9139-4f54-a1e1-14d82c96fcd8)

**Comment by JuanGarriuz** [comment]
In monitoring, the allowAgent filter is continuously being added when changing the date range.

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/71e54c40-e064-4be7-8346-2035c37c6415)

**Comment by Desvelao** [comment]
The filter related to `hideManagerAlerts` is not considered for the `Evolution` visualization: 
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/34042064/f6bd43c3-9fae-4589-b070-9331e5054f0d)

**Comment by Desvelao** [comment]
WIP patch:
[hide-server-data-events-tab.txt](https://github.com/wazuh/wazuh-dashboard-plugins/files/14343002/hide-server-data-events-tab.txt)

This could fix the problem about missing filter related to `hideManagerAlerts`.

We saw some problems with repeated filters on `Evolution` visualiz<ation.

This needs a deeper analysis.

Due to this problem happening in previous versions and this will change in 4.9.0, I will leave the issue on hold until we decide what to do.

**Comment by asteriscos** [comment]
This will be solved in this issue:
-https://github.com/wazuh/wazuh-dashboard-plugins/issues/6499

I'm closing this.
