### ISSUE TITLE
[Remove discover] Implement embeddable dashboard on configuration assessment module

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6479]
## Description

We have to check if there are any _kibana-integrations_ components on the configuration assessment module. If any _kibana-integrations_ is found we need to refactor it to use the new embeddable dashboard component.

## Tasks

- [ ] Implement the embeddable dashboard on configuration assessment

**Comment by yenienserrano** [comment]
I am still analyzing because it seems that it is not necessary to replace it because they are charts created with d3 and custom tables.

**Comment by yenienserrano** [comment]
It is not necessary because it does not use kibana integration.
