### ISSUE TITLE
Standardize filter management mechanisms

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6499]
## Description

We need to refactor and standardize the filtering mechanisms so all the embeddable dashboards and reports can make use of the filter state without using any of the legacy methods. This is a step forward towards deprecating the Discover legacy, AngularJS, and also integrating the new embeddable dashboards with the PDF reports.

### Functional requirements

- The filter system must consider the search bar filters
- The filter system must consider the hideManager alerts configuration
- The filter system must consider if an agent is pinned
- The filter system must consider the allowed agents by RBAC
- The filter system must consider the selected cluster

**Comment by Machi3mfl** [comment]
## Scope

The aim is to generate a standard solution that allows each system module (such as vulnerabilities) to manage its own data source.
It is important that the solution is standard and allows:

- Retrieving filters (getFilters)
- Fetching data (fetchData)

The goal is for each module to be able to manage its own data source, to be able to decouple, decentralize, and give responsibility to each module for its own data source.

**Comment by Machi3mfl** [comment]
# Create a generic solution design (⏳ in progress)

## Data source filter manager

Is a class that is responsible for managing the filters of a data source (Important: the filters are not managed by the data source itself, it's managed by the filter manager). This allows the filters to be managed in a centralized way but at the same time makes it responsive to the data source to define its filters.

## Use cases

- The data source filter manager receives a data source and the filters from the filter manager or another source. The filters have the type Filter.

- When the data source filter manager receives the filters:
    - Filter the filters received and only keep the filters that was added by the user. 
        Condition: When the filter not have the property meta.controlledBy, $state.isImplicit and the meta.index is not the same as the data source index pattern.
- Then is able to: 
   - Retrieve the filters applied by the user and the data source filters (For instance: the vulnerabilities module). Every module has the responsibility to manage its own filters.
   - Fetch the data from the data source using the filters and add extra filters that are not visible to the user. 
        For instance: hide manager, pinned agent, allowed agents, etc.

## Solution

```ts 

    type tDataSourceFilterManager = {
        fetch: () => Promise<any>; // this fetch the data from the data source using the fetch filters
        setFilters: (filters: tFilter[]) => void;
        getFixedFilters: () => tFilter[]; // this retreive only the fixed filters for the specific data source (pinned agent)
        getFilters: () => tFilter[]; // this retreive the filters visible to the user (fixed filters and user filters)
        getFetchFilters: () => tFilter[]; // this retreive the filters that are used to fetch the data (fixed filters, user filters and extra hidden filters)
    }

    const dataSourceFilterManager = new DataSourceFilterManager(dataSource, filters);
    
    const dataSourceFilters = dataSourceFilterManager.getFilters(); // this can be use to show the filters in the search bar
    const data = dataSourceFilterManager.fetch();
```

**Comment by Machi3mfl** [comment]
# Create a generic solution design (⏳ in progress)

## Data source hook

Create a react hook that:
- simplifies the use of data sources, related filters, fetching data
- reduce the boilerplate

```tsx

type tUseDataSourceLoadedReturns = {
    isLoading: boolean;
    dataSource: tDataSource;
    filters: tFilter[];
    fetchFilters: tFilter[];
    fixedFilters: tFilter[];
    fetchData: () => Promise<any>;
    setFilters: (filters: tFilter[]) => void;
}

```

## Unit tests 

in progress ⌛

**Comment by Machi3mfl** [comment]
# Implemented on Vulnerability Detection Module

https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/b5540185-ff59-4301-801c-ade1f0c37948

This solution uses the new: 

- Data Source solution
- useDataSource hook
- Wazuh discover with useDataSource hook added

**Comment by Machi3mfl** [comment]
# Add unit tests to the final solution

<img width="764" alt="Screenshot 2024-03-31 at 15 08 54" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/8a73687e-62b6-4166-a0fc-5a74359ee759">
<img width="622" alt="Screenshot 2024-03-31 at 15 08 48" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/6d2f82e2-8239-4b1e-857e-53aa51ed1a0e">
<img width="642" alt="Screenshot 2024-03-31 at 15 08 40" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/a5e9f049-cdbb-415d-b5ee-dd547260326d">
<img width="647" alt="Screenshot 2024-03-31 at 15 08 32" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/da6afb45-0376-463f-a09f-e9bd42a7f387">
<img width="979" alt="Screenshot 2024-03-31 at 15 08 24" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/8cc1b1fa-4bff-411e-82f1-0e3ec98f2cda">

**Comment by Machi3mfl** [comment]
# How to use the new data source solution

(Coming soon ⏳)
