### ISSUE TITLE
Vulnerability Detection dashboard summary misleading use of alerts

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-dashboard-plugins#6531]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | beta4 | Any |

**Description**

The vulnerability detection dashboard summary incorrectly employs the term "alert." The panel's purpose is to showcase active vulnerabilities within the environment, not alerts.

This issue gains heightened significance following the recent changes introduced in https://github.com/wazuh/wazuh/pull/21989. The continued use of the term "alert" has the potential to create confusion among users.

**Steps to reproduce**
1. Navigate to Vulnerability Detection
2. Check the summary report

**Screenshots**
![alerts](https://github.com/wazuh/wazuh-dashboard-plugins/assets/11089305/d88630e0-cdf8-4d61-b6d4-b830548a7fe7)

**Comment by JuanGarriuz** [comment]
This change has already been addressed in the following issue: [Refine vulnerabilities dashboard](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6533)
