### ISSUE TITLE
[Remove discover] Implement new PDF reports in dashboards

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6556]
#  Description
We need to adapt the current PDF report features so it can generate reports from embeddable dashboards. This will allow us to progressively deprecate the legacy discover dependencies and deprecate AngularJS in the plugins.

## Implementation restrictions

- The PDF reports capability must not use any AngularJS related feature.

## Tasks

- [x] Adapt the existing PDF report feature to use embeddable dashboards
- [x] Adapt the generation of PDF reports
  - [x] modules
  - [x] groups
  - [x] agents inventory
  - [x] configuration

**Comment by Desvelao** [comment]
# Changes

- Replace query.getOpenSearchQuery from global source to use the search context
- Update the development branch with latest changes of `4.9.0` branch

**Comment by Desvelao** [comment]
# Problem

After updating the development branch and trying to generate the PDF report on Theat Hunting application that has already replaced the dashboard, I got errors. It seems the old dashboard is rendered and causes that take screenshots of visualizations that are not rendered, and this causes a problem when building the PDF report on the backend side.

This issue https://github.com/wazuh/wazuh-dashboard-plugins/pull/6594 should remove the render of the old dashboard, and this problem should disappear.

**Comment by Desvelao** [comment]
# Changes

- Update the development branch with the latest changes of `4.9.0` branch
- Adapt the generation of PDF reports using the data source on:
 - Dashboard of Threat Hunting and VirusTotal
 - Adapt the generation of PDF reports of agent inventory using the data source
  - Fix error in time range filter when using the `Today` and `This week` special date ranges

**Comment by Desvelao** [comment]
# Problem

I found a problem on the generation of PDF report of Amazon Web Services related to the geolocation map visualization. It seems the library to convert the DOM node to image fails. I reviewed the previous versions and this visualization is not included on the reports.

I will try to research if we can solve this.

**Comment by Desvelao** [comment]
I continue researching about the problem related to converting to png the map visualization on the Amazon Web Services application.

I found an issue abut the error: https://github.com/tsayen/dom-to-image/issues/455

**Comment by Desvelao** [comment]
# Changes

- Dashboard of File Integrity Monitoring

**Comment by Desvelao** [comment]
# Changes

- Dashboard of Malware Detection

**Comment by Desvelao** [comment]
# Changes
- Update the development branch with the latest changes of `4.9.0`
- Dashboard of Google Cloud
- Fix an error with the summary alerts table related to https://github.com/wazuh/wazuh-dashboard-plugins/issues/6457

**Comment by Desvelao** [comment]
# Changes
- Update the development branch with the latest changes of `4.9.0`
- Dashboard
  - PCI
  - GDPR
  - HIPAA
  - NISTR 800-53
  - TSC
  - GitHub
- Fix a problem with the main request to get if there is available data on the GitHub > Dashboard

**Comment by Desvelao** [comment]
# Changes
- Update the development branch with the latest changes of `4.9.0`
- Dashboard
  - Office 365
- Add missing button to generate report on Office 365 > Dashboard
- Add support for agents to the Office 365

**Comment by Desvelao** [comment]
# Problem

The change of system to render the dashboard has caused the data contained in the visualizations of table type can not be accessed, so it can not be sent to the backend side to generate the table with all the pages that could be visible though pagination on the frontend side.

**Comment by Desvelao** [comment]
# Update

- Research a problem related to missing button to generate the report. More info: https://github.com/wazuh/wazuh-dashboard-plugins/pull/6558#issuecomment-2114721998

**Comment by Desvelao** [comment]
# Changes
- Update the development branch with the latest changes of `4.9.0`
