### ISSUE TITLE
The selected option in the Dev Tools API Console does not change using the keyboard arrow keys

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-dashboard-plugins#6586]
| Wazuh | Rev  | Browser                      | SO |
|-------|------|------------------------------|--|
| 4.7.3 | 40714 | Firefox |Pop_OS! 22.04|

**Description**

When trying to use the keyboard arrows in the API Console command list in the Wazuh user interface, the options in the list do not change, resetting to the first position for each press (see video for reference)

**Preconditions**
1. Use the v4.7.3 OVA

**Steps to reproduce**
1. Navigate to `/app/wazuh#/wazuh-dev?tab=devTools`
2. Write `GET /syscollector/`
3. In the dropdown, use the up and down keyboard  arrow keys
4. Click the `antepenultimate` option
5. Use the up/down keyboard arrow key

**Expected Result**
1. The selected option should change using the keyboard arrow keys

**Actual Result**
1. The selected option does not change using the keyboard arrow keys

**Screenshots**

https://github.com/wazuh/wazuh-dashboard-plugins/assets/14913942/fbe41917-32ce-4cd4-9136-fc38d9c1d7a5

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/14913942/6d85474b-1cb4-49f3-b113-29a1c9bd64cb)

**Additional context**

This behavior does not happen in `Brave 1.64.113`

**Comment by gdiazlo** [comment]
Unable to reproduce on Firefox macOS and Windows, with the same version 124.0.1.
