### ISSUE TITLE
Home visualizations load twice

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6588]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 07 | - |

# Description
Whenever a user logs in and the overview home page loads, the KPIs and the agent visualization are loaded twice. This seems to happen only after the initial health-check and the initialization of the kibana-discover legacy.
We have to fix this, so the components only load once.

### Steps to reproduce
1. Log in Wazuh Dashboard
2. See the Overview home visualizations load twice after the health-check finishes

**Expected Result**
1. The visualizations must only load once

**Actual Result**
1. The visualizations load twice

### Screenshots

![Peek 2024-04-11 18-54](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/48285466-1993-4777-9b04-94852d33d956)

#### Double requests

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/610536fa-6b60-4674-976c-b0a097c6fb40)

#### Initiators

health-check
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/29dd0623-3cb8-4807-9555-53e2048dc279)

kibana-discover state sync
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/095a2f76-e1bc-488e-b024-cd480e538e56)

**Comment by yenienserrano** [comment]
I am investigating who is causing the double rendering of the view.

**Comment by yenienserrano** [comment]
Doing some research and making comparisons with `4.7.3` we could see that in `4.8.0` more redirects are being made when logging in that cause double rendering.

in `4.7.3` you can see 2 redirections to the `overview` when logging in, one is from the `healtcheck` to the `overview` without parameters and the second is the same but with all parameters:

<img width="323" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/5f950e75-7a10-4bd2-b469-f86192f83606">

<img width="538" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/a7af66bd-6ccd-4d0b-96a9-6d471847003c">

<img width="525" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/26f6fea3-c2a8-469c-b46d-a87058bff8b5">

in `4.8.0` it makes 4 redirections in the `general` view from the login, one is from the `healtcheck` to the `general` view without parameters, the second is the same but with the parameters of the view without the filters, the third from the `overview` to the `/` where only the filters arrive and finally from the `/` to the `overview` where it would already have all the parameters.

<img width="264" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/ff3e3f71-364f-4419-b612-53ddd886e618">

<img width="481" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/ad3ba4db-f475-47c4-a17d-7658776a9a2e">

<img width="485" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/277f63d2-6723-4ac9-9f77-59b97d0b1c07">

<img width="481" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/b4995b60-b9ac-46c6-9c76-f3014edd36e5">

<img width="462" alt="image" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/410daa1f-96fd-4e80-b640-40f653deee35">

**Comment by yenienserrano** [comment]
I was checking and the [commit](https://github.com/wazuh/wazuh-dashboard-plugins/commit/7b12b0d6d4baf79751ae0de6f8dc0474cd7c5cff) before the menu change was working as expected and after this [commit](https://github.com/wazuh/wazuh-dashboard-plugins/commit/8651d16310000986658987d097fb539b91589dc2) it started to make the 4 redirects.

**Comment by yenienserrano** [comment]
Apparently the one that causes the redirects is the `[syncHistoryLocations](https://github.com/wazuh/wazuh-dashboard-plugins/blob/4.8.0/plugins/main/public/plugin.ts#L155)` function that I added because of a problem navigating between Wazuh modules due to discover legacy.

And from the tests I've been running, it does the redirections when the [createHashHistory](https://github.com/wazuh/wazuh-dashboard-plugins/blob/4.8.0/plugins/main/public/kibana-integrations/discover/kibana_services.ts#L80) is executed.
