### ISSUE TITLE
`Delay` body parameter in `PUT /cluster/restart`

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-dashboard-plugins#6605]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| X.Y.Z | xyzw | Chrome, Firefox, Safari, etc |

**Description**
When the dashboard restarts the cluster through the API, it sends a `{"delay": 1500}` body, which is completely ignored since said endpoint does not expect a body:
```
2024/04/19 08:20:15 INFO: wazuh-wui 172.19.0.4 "PUT /cluster/restart" with parameters {} and body {"delay": 15000} done in 0.020s: 200
```

This happens at least when clicking the restart button after modifying a rule, although it might behaves the same way in other use cases. Also, when the **cluster is disabled**, `PUT /manager/restart` is used instead without body:
```
"PUT /manager/restart" with parameters {} and body {} done in 0.012s: 200
```

**Preconditions**
1. Enable clusterd in the manager's `ossec.conf` and restart it.

**Steps to reproduce**
1. Navigate to Management > Rules > Edit any rule file.
2. Save and restart cluster.
3. Check `api.log`, the delay parameter is included in PUT /cluster/restart.

**Expected Result**
1. The body should be empty for PUT /cluster/restart.

**Actual Result**
1. It contains a useless parameter, `delay`.

**Comment by Desvelao** [comment]
# Research

The `delay` parameter is used by the plugins (frontend and backend side) and defines the minimum elapsed time that the request should be delayed. This is used by the actions to restart the cluster ( previous to edit rules, files, cdb lists allowing the sync of the files) or delete the user API token.

The parameter is not removed of the plugins management, as a result, this is sent as the body of the server API request.

**Comment by Desvelao** [comment]
# Update 2024/06/19

- Fix typos on pull request https://github.com/wazuh/wazuh-dashboard-plugins/pull/6778
