### ISSUE TITLE
How to Disable Wazuh dashboard basic authentication

### ISSUE THREAD

**Issue by NLTsankar** [wazuh/wazuh-dashboard-plugins#6656]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| X.Y.Z | xyzw | Chrome, Firefox, Safari, etc |

**Description**
Short description of your issue.

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to '...'

**Expected Result**
1. 

**Actual Result**
1. 

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by yenienserrano** [comment]
Duplicated in https://github.com/wazuh/wazuh-dashboard-plugins/issues/6657
