### ISSUE TITLE
How to disable Wazuh dashboard basic authentication

### ISSUE THREAD

**Issue by NLTsankar** [wazuh/wazuh-dashboard-plugins#6657]
## Description
We need to ensure the UI compatibility with the next version of Elastic vX.X | OpenSearch vX.X.
This update is still being discussed, but we need to be aware of potential issues.

For that, we need to:

- [ ] Review opensearch and opensearch-dashboard latest stable changelog. 
- [ ] Identify improvements and potential impact on the UI.
- [ ] Develop a testing environment to verify our components would work under this new build.

## Issues
-  _List here the detected issues_

**Comment by NLTsankar** [comment]
Any one please step-by-step explain to fix this issue. How do I disable Wazuh Dashboard Basic Authentication?

**Comment by yenienserrano** [comment]
Hi @NLTsankar, we don't recommend you to use basic authentication for security reasons, but if you want to do so you can see how to set it up here.
https://opensearch.org/docs/2.8/security/configuration/disable/
