### ISSUE TITLE
Change tag format to use vx.x.x

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6673]
## Description
Currently we have script that automate the tag generation and they use the following format:
`v{Wazuh_mayor}.{Wazuh_minor}.{Wazuh_path}-{Opensearch_mayor}.{Opensearch_minor}.{Opensearch_patch}`

We must change this to user only Wazuh version as the name of the tag:
`v{Wazuh_mayor}.{Wazuh_minor}.{Wazuh_path}`

## Tasks
The steps that have to be completed in order to close the issue.

- [x] Change tag handling script to use only Wazuh version as the name of a tag. E.g. v4.9.0
- [x] Analyze how this impacts documentation

**Comment by Desvelao** [comment]
# Adapt the tag script

I adapted the tag script to match with the new tag naming convention and updated the related documentation of `RELEASING.md`

**Comment by Desvelao** [comment]
# Analysis of the impact on Wazuh documentation

I reviewed the references to the tags of the `wazuh-dashboard-plugins` repository and I found some related to link to the CHANGELOG.md file of the tag such as https://github.com/wazuh/wazuh-documentation/blob/4.9.0/source/release-notes/release-4-7-4.rst?plain=1#L32.

I asked to the documentation team about if we need to do some changes in the documentation.

**Comment by Desvelao** [comment]
# Wazuh dashboard build

The process to build the Wazuh dashboard build could need to adapt to use the new tag naming convention of `wazuh-dashboard-plugins`.

**Comment by Desvelao** [comment]
# Wiki

I added a reference to the new tag naming convention on the wiki https://github.com/wazuh/wazuh-dashboard-plugins/wiki/About-our-branches-and-tags#tags.

I added some missing and (legacy) naming conventions related to Wazuh dashboard packages.

**Comment by Tostti** [comment]
# Wazuh dashboard build 

Currently the building process requires to manually enter the branch/tag/commit for the plugins repository. There are no needed modifications.

**Comment by Desvelao** [comment]
# Changes
- Update the development branch with the latest changes of `4.9.0`
