### ISSUE TITLE
Home overview show breadcrumb configuration assessment information

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6676]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 10 | `Safari` |

**Description**
When the user navigates to the **Configuration Assessment** view using the **Overview Home** card, then selects an agent and goes back to the Home view, the **Overview Home** breadcrumb gets stuck with the **Configuration Assessment** breadcrumb and the pinned agent. Also the URL keeps showing the configuration assessment URL.

**Preconditions**
1. Have agents 

**Steps to reproduce**
1. Go to Configuration assessment
2. Pin an agent
3. Go to Home view
4. Check the breadcrumb and URL

**Screenshots**

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/cf383d0b-fba1-4dd7-a282-5c50f7ee6125)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/120197b2-722e-4c91-a963-80ef3f3a12e9)

**Comment by JuanGarriuz** [comment]
## Research 

### Testing with 4,10 and chrome bug can't be reproduced

https://github.com/user-attachments/assets/6c74a83b-c251-430c-ab42-8fa259220238
