### ISSUE TITLE
New discover table gets hidden in small height viewports

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6740]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 00 | Chrome, Firefox, Safari, etc |

## Description
The new discover table gets hidden from the view with no scroll available when the viewport has a small height. We need to adjust the styles so the adapt properly to the viewport.

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/cf1819e4-8216-49b4-bac7-3717e9cbc551)

**Comment by JuanGarriuz** [comment]
## Update 04/06

A height prop added to the event table to fix the problem.

#### To Do:

- [] Check render in all events tables.
- [] Changelog

**Comment by JuanGarriuz** [comment]
## Update 05/06

<details><summary>Investigate double scrollbar bug</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/30141dcd-1bd4-4a51-9658-bf4dac84dab2)


</details>
