### ISSUE TITLE
Quick change between dashboard tabs error 

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6744]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 00 | Chrome, Firefox, Safari, etc |

**Description**
Switching quickly between **Dashboard** and **Events** tabs throws an error and doesn't load the visualizations.

<details>
<summary>Screenshots</summary>

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/8f86f52f-b9be-4857-a43b-8dd905749327)

![Peek 2024-06-04 17-23](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/7665531b-edcc-4b2f-8a28-9f4f5e731dfa)

</details>

**Comment by yenienserrano** [comment]
I left a query on the opensearch dashboard slack to see if they knew about the error.
https://opensearch.slack.com/archives/C01QENNTGUD/p1717526144724889

**Comment by yenienserrano** [comment]
I was doing some tests and it seems that the problem is due to the conditional rendering of the dashboards, when changing tabs quickly they are not rendered but it tries to destroy them afterwards and that's why the error occurs.

**Comment by yenienserrano** [comment]
I have been working on the proposals and I leave the patch of proposal 1 and the patch of proposal 2 in one dashboard.
[patch-render.txt](https://github.com/user-attachments/files/15686258/patch-render.txt)
[patch-style.txt](https://github.com/user-attachments/files/15686262/patch-style.txt)

**Comment by yenienserrano** [comment]
It was decided to go ahead with the proposal that changed less the visual behaviour, which is to always render the dashboards but if there is no data to keep them hidden and show the corresponding warning.


https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/34864983-7bc4-48b7-8fb3-1a537cef1e45
