### ISSUE TITLE
Implement new discover table in FIM inventory flyout

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6749]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 00 | - |

# Description

We need to implement the new <WazuhFlyoutDiscover/> component in the File integrity monitoring Inventory flyout.

## Screenshot

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/22c86ec9-25b8-46b4-a356-7186196bee12)

**Comment by Desvelao** [comment]
# Update 2024-06-10

- Replace the discover table on the FIM inventory flyout
