### ISSUE TITLE
Safari sometimes crashes when you change index pattern

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-dashboard-plugins#6769]
**Description**

When you change index pattern in safari it sometimes crashes and you have to close the browser. 

**Preconditions**
1. Use Safari

**Steps to reproduce**

Change index pattern until browser crashes

https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/bb4a260a-e5b0-4b9c-aba7-6430086a9568

**Comment by yenienserrano** [comment]
I was investigating and comparing with 4.8.0 and with real managers, for now the only thing I could see is that when doing the window.location.reload() sometimes fails, before it was using the this.router.reload() which was from the angular router.

**Comment by yenienserrano** [comment]
Apparently safari is having problems with window.location.reload() which is the same as reloading the page from the button. And this behaviour was tested and is happening too


https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/13bbe7a8-a451-4480-b37e-bc6ca28e4d18

**Comment by yenienserrano** [comment]
I was testing in a production environment with 4.9.0 and could not reproduce the error.

**Comment by asteriscos** [comment]
I will close this issue because not only cannot be replicated in production packages, but also seems to be related to a Safari window.location.reload problem.
