### ISSUE TITLE
Switching tabs in the same module encodes the URL

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6773]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 00 | Chrome, Firefox, Safari |

# Description

When the user clicks on the Dashbords or Events tab the URL special characters get encoded. We need to fix this so that the string of filters applied is represented the same way OpenSearch does.

## Screenshot

![Peek 2024-06-14 10-55](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/752a475d-1a3c-42bb-a8f7-4580c0c8fd09)

**Comment by chantal-kelm** [comment]
It was found that this happens not only in the Events tab of each module but also in other parts of the application and will be fixed in the same issue with a more global solution:

Rules
Health-check
FIM Inventory tab table
Endpoint summary > Configuration
