### ISSUE TITLE
Home overview KPI's link don't work with custom index-pattern

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6776]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 12 | Chrome, Firefox, Safari |

# Description

With a custom alerts index pattern, the Overview Home link doesn't work properly. The `rule.level` seems to apply the default alerts index pattern and throws an error because it doesn't exist.

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/bd6ac700-87f2-4681-882e-13355fda8542)

The issue seems to be related to this:
https://github.com/wazuh/wazuh-dashboard-plugins/blob/v4.8.0-2.10.0/plugins/main/public/controllers/overview/components/last-alerts-stat/last-alerts-stat.tsx#L90

**Comment by Desvelao** [comment]
# Update 2024/06/17

- Fixed the hardcoded value of an index pattern in a filter on the KPI link
- Fixed an error when using an index pattern with a different title and id
