### ISSUE TITLE
Vulnerability dashboard KPI's colors don't reflect the severity properly

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6779]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 12 | Chrome, Firefox, Safari, etc |

**Description**
The Threat Intelligence / Vulnerability detection dashboard top KPI's colors can be improved to quickly interpreter the severity of the alerts. Currently the colors are as follows:

#### Current
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/d2280fca-cc59-44d2-b970-29da225db381)

The High severity KPI has a blue color and it can easily be misinterpreted. 

We propose to change the Vulnerabilities KPIs colors to match the same pattern as the home overview colors:

Critical: Red
High: Yellow
Medium: Blue
Low: Green

#### Expected

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/6057be1f-973f-473b-9c4d-a991a248fb31)

**Comment by Desvelao** [comment]
# Research

The metrics visualizations use ranges and color schemas. This means the color of the value could vary depending on the range. For these metric visualizations, the color it is the same without regarding the value. It is not possible to set a specific color. Moreover, the color schema tones could vary according to the theme version or theme (dark/light).

If we want to match the vulneravility severity level on the metrics and the history visualization, we can:
- History visualization: define the specific color for each severity level
- Metric: set the specific color (matching with the defined on the history visualization) using styles to overwrite the specific color.

## Result

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/34042064/8cd81ef2-1dce-4df4-b4ba-5acc5ac2c39e)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/34042064/921178ad-c48e-4f89-8a99-e2d6f4da2000)

## Patch
[vulnerability-dashboard-kpi-history-vis-severity-colors.txt](https://github.com/user-attachments/files/15898886/vulnerability-dashboard-kpi-history-vis-severity-colors.txt)

**Comment by Desvelao** [comment]
# Update 2024/06/20

I created a pull request based on the solution proposed on https://github.com/wazuh/wazuh-dashboard-plugins/issues/6779#issuecomment-2178282265.

- Force colors on metric visualizations through HTML styles
- Define colors of the historical visualizations
