### ISSUE TITLE
Convert Vulnerability Detector references fields into hyperlinks 

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh-dashboard-plugins#6784]
## Description
A user suggested that the reference field containing hyperlinks is not clickable. This seems to be related to the type of field used on the dashboard

It would be a great improvement for the user to be able to click on links and open them on the spot

### Current status
![image](https://github.com/wazuh/wazuh-dashboard/assets/34063881/f71d1943-f5a7-4344-817e-ba61a6ce7fce)

**Comment by gdiazlo** [comment]
We need to work in templates for well-known documents, instead of the raw representation we have now.

**Comment by misje** [comment]
![old ui](https://01679260923621869060.googlegroups.com/attach/2ff6c7d37f7b5/Capture.PNG?part=0.1&view=1&vt=ANaJVrH8bvXmdJYpEBuYXRel_TS1z0Wylc5j6zjkVZNlJSuBoEW8CREmxaQzfTv1deCfGYc5WmzzA1kBJkjcXE-ohPClEbJgqSGfn-g69QhlREYLVwtW9lA)

This is how the old interface looked like. I am pretty sure that the external reference section provided clickable links. The new interface is pretty much just a raw event view.
