### ISSUE TITLE
CONFIGURATION ASSESSMENT DASHBOARD - Suggestion

### ISSUE THREAD

**Issue by SamsonIdowu** [wazuh/wazuh-dashboard-plugins#6794]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0 | Wazuh configuration assessment dashboard | All | All | All |

### Problem:
**Wazuh configuration assessment** currently requires a user to select an agent in order to display configuration assessement. 
Below is an image showing the current modus operandi:

![image](https://github.com/wazuh/wazuh/assets/66468924/571c6167-df7a-4891-913a-5884aeadf734)

### Suggestion:
A user should be able to view configuration assessment based on some other criteria such as the following:

1. Agent groups
2. All agents
3. Agent OS
4. Agent name

A user should be able to find common configuration errors for multiple endpoints and filter with agent name to get an endpoint specific assessment.

### Justification:
I have 500 monitored endpoints including Linux, macOS, and Windows endpoints. Why do I have to select a single agent to be able to make a configuration assessment?

My infrastructure is large and I should be able to get a dashboard with an overview of configuration assessment for my endpoints based on the earlier suggested criteria.

**Comment by gdiazlo** [comment]
This is being worked on for a future release of Wazuh. The development has already started. The main issue is in https://github.com/wazuh/wazuh/issues/22887 the SCA module will store all its data in wazuh-indexer, enabling the features you describe in your issue. 

I am closing this one in favor of:
- https://github.com/wazuh/wazuh/issues/22887
