### ISSUE TITLE
The back button displays the login page

### ISSUE THREAD

**Issue by JuanGarriuz** [wazuh/wazuh-dashboard-plugins#6796]
### **Description**

When go back more than two times, the dashboard renders the login page.

### **Preconditions**

Use Chrome browser

### **Steps to reproduce**
1. Navigate to some module two or more times
2. Press the back button on the browser two or more times.
3. The login page must be rendered.

### **Expected Result**

The page renders the expected view (the third-to-last page visited).

https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/c1b99713-4de8-4e5f-9bd8-0bfa5669ea13

### **Actual Result**

The login page be rendered

https://github.com/wazuh/wazuh-dashboard-plugins/assets/124377319/2e22936b-0ba2-403d-9f5a-27e65391388f

### **Additional context**

The redirect button works correctly in the Firefox browser and in the Explore applications (OpenSearch).

**Comment by Desvelao** [comment]
# Research

I was testing this on `4.9.0` and I could not replicate it.

Using Google Chrome 126.0.6478.61, I experienced a rare behavior I think @JuanGarriuz saw too a few days ago. Clicking on the back button could cause the back button is disabled. Clicking on the window page, the button could be enabled again.

Using Firefox 127.0b9, the back button worked as expected.

**Comment by Desvelao** [comment]
I updated the development branch `4.9.0` with the latest changes #6771 and these could have caused the problem was solved on Google Chrome.

Using Firefox, I could not replicate it.

**Comment by yenienserrano** [comment]
Test:

https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/6cee155f-d467-463c-960e-ad0904ecc549

<img width="286" alt="Screenshot 2024-07-01 at 3 05 52 PM" src="https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/ba1164d4-b6eb-4bd3-aca8-25f530ea009b">

**Comment by Desvelao** [comment]
I will close the issue because the problem is not present anymore according to the provided evidences.

**Comment by jbiset** [comment]
## Testing with the latest changes #6771 :green_circle: 

[evidence.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/867d495f-5eb5-4e31-93b3-4048ec248b25)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/4a159bc1-a522-4556-b22e-c5513ca8a727)
