### ISSUE TITLE
Error creating default wazuh-security-events dashboard in Splunk

### ISSUE THREAD

**Issue by efahnle** [wazuh/wazuh-dashboard-plugins#6804]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | - | - |

**Description**
Community user reported a problem following the guide on [Splunk Integration](https://documentation.wazuh.com/current/integrations-guide/splunk/index.html) when trying to create a dashboard on Splunk, using the default wazuh-security-events dashboard provided by the guide: https://packages.wazuh.com/integrations/splunk/4.x-9.x/dashboards/wz-sp-4.x-9.x-wazuh-security-events.

**Preconditions**
1. This has been tested originally on Wazuh 4.8.0 and Splunk Enterprise v9.21

**Steps to reproduce**
1. Perform the integration using a universal forwarder as stated in the guide.
2. Verify data is being sent to Splunk.
3. Create a dashboard for [wz-sp-4.x-9.x-wazuh-security-events](https://documentation.wazuh.com/current/integrations-guide/splunk/index.html#splunk-dashboards) 

**Expected Result**
1. Splunk's dashboard works correctly

**Actual Result**
1. An error `[/inputs/input_global_trp/options]: must NOT have additional properties, [/inputs/input_global_trp]: must match "then" schema` is shown

**Screenshots**
(Screenshot provided by the user)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/31556780/b972ad2b-29b0-430b-9881-d2daf86e3bb4)

**Additional context**
- There are no errors on `/opt/splunkforwarder/var/log/splunk/splunkd.log`
- No modifications were done to the dashboard file
- Reporter: https://github.com/wazuh/community/issues/28505

**Proposed workaround**
From this section here:
```
  "inputs": {
    "input_global_trp": {
      "type": "input.timerange",
      "options": {
        "token": "global_time",
        "defaultValue": "-60m@m,now",
        "queryParameters": {
          "latest": "$global_time.latest$",
          "earliest": "$global_time.earliest$"
        }
      },
      "title": "Global Time Range"
    }
  },
```

Inside `inputs.input_global_trp.options`, this should be deleted:
```
        "queryParameters": {
          "latest": "$global_time.latest$",
          "earliest": "$global_time.earliest$"
        }
```

So the remaining config would look like this:
```
  "inputs": {
    "input_global_trp": {
      "type": "input.timerange",
      "options": {
        "token": "global_time",
        "defaultValue": "-60m@m,now"
      },
      "title": "Global Time Range"
    }
  },
```

**Comment by JuanGarriuz** [comment]
### Reproduce Issue


https://github.com/user-attachments/assets/f777492c-8347-4b22-9fa7-d2ef9beb4c3c

**Comment by JuanGarriuz** [comment]
### 9.0.4

![image](https://github.com/user-attachments/assets/fcd13092-3e58-4b25-a53f-10c809d531f3)

**Comment by JuanGarriuz** [comment]
To reproduce with diferents versions it we need follow this steps:


- Search splunk <version> on browser. Click on official links.
- Ctrl + u
- Search link download installation and copy
- In dashboard repository > Docker > Integrations > docker-compose.yml change splunk image version.
- In dashboard repository > Docker > Integrations > .env change SPLUNK_FORWARDER_URL with URL copy in step 3
- Run `docker compose up -d`

**Comment by JuanGarriuz** [comment]
To solve it in documentation QueryParams must be removed from "inputs" in [wz-sp-4.x-9.x-wazuh-security-events](https://documentation.wazuh.com/current/integrations-guide/splunk/index.html#splunk-dashboards)


Something like:

```
{
 [...]
  "inputs": {
    "input_global_trp": {
      "type": "input.timerange",
      "options": {
        "token": "global_time",
        "defaultValue": "-60m@m,now"
      },
      "title": "Global Time Range"
    }
  },
  [...]
}

```
