### ISSUE TITLE
Agent version shows red status when up to date

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh-dashboard-plugins#6866]
**Description**
The agent version status is incorrectly displayed as red (outdated) even when it is actually up to date. 

**Steps to reproduce**
1. Go to the Endpoints Summary.
2. Verify the agent version status.
3. Observe that the status is red despite the agent being up to date.

**Expected Result**
![image](https://github.com/user-attachments/assets/65e81e5d-cf24-480e-a9f3-8f6e72d20002)

**Actual Result**
The agent version shows a red status when it is actually up to date
![image](https://github.com/user-attachments/assets/4c598f85-a594-48b6-a806-3b1ede0cc302)

**Comment by lucianogorza** [comment]
## Reproduce the bug

I can reproduce the bug with a CentOS agent.

![image](https://github.com/user-attachments/assets/1240f4d8-7273-4ff5-8f1f-6131bc6ee5ed)

**Comment by lucianogorza** [comment]
Apparently it's an API issue, so it will be resolved at https://github.com/wazuh/wazuh/issues/24914

**Comment by lucianogorza** [comment]
Test before update manager with changes from https://github.com/wazuh/wazuh/pull/24946
![image](https://github.com/user-attachments/assets/c4f0c504-3b31-45ac-bdd1-fe434bcd22ce)

After apply changes

**Comment by asteriscos** [comment]
This problem was solved by a pull request made by @wazuh/devel-pyserver in Wazuh API. No work is needed on the Wazuh Dashboard side. I'm closing this as not planned.
