### ISSUE TITLE
Selected rule flyout state is inconsistent in the URL

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6885]
## Description

When navigating from the event table to a `rule.id` it redirects you to Rules app and opens a flyout with the selected rule.id, but when you close the flyout the URL still has the selected `rule.id`.

This issue aims to manage the state of the ruleset flyout using the URL as a source of truth, instead of using a local state.

**Steps to reproduce**
1. Navigate to 'some module > events'
2. Click on 'some value of rule.id'
3. Close the flyout

**Expected Result**
- Should return to the previous view after the first click
- If the flyout is closed the URL shouldn't have a rule.id
- If the flyout is opened the URL should have a rule.id

**Actual Result**
1. Closing the flyout doesn't clear the URL
2. Selecting another rule doesn't update the URL

**Screenshots**

![image](https://github.com/user-attachments/assets/3bda82fe-5ea4-417b-a6fb-3dc9bcf4ee5e)

**Comment by Desvelao** [comment]
# Research

The rule details flyout render was based on an internal component state and supported the selection of a specific resource through the `redirectRule` query parameter.

Moreover there was an inconsitency when the same flyout was opened using the Rule main table.

We want to ensure the same behavior for the render of the rule details flyout and this must be based on the URL.
