### ISSUE TITLE
Agent registration password includes `\n`

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6906]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 05 | Chrome, Firefox, Safari |

**Description**
If Wazuh agent enrollment password is enabled the registration script renders a `\n` in a macOS password.

**Preconditions**
1. Enable an agent registration password

**Steps to reproduce**
1. Navigate to Endpoints summary
2. Click on **_Deploy new agent_**
3. Select macOS

**Expected Result**
1. There should be no `\n` character

**Actual Result**
1. There's a `\n` at the end of the password

#### Additional context
Registration command service:
https://github.com/wazuh/wazuh-dashboard-plugins/blob/4.9.0/plugins/main/public/components/endpoints-summary/register-agent/services/register-agent-os-commands-services.tsx#L152

**Screenshots**

![image](https://github.com/user-attachments/assets/346e820c-706b-407a-b0b1-fdf9838774f7)

**Comment by Desvelao** [comment]
The `\n` character in the `echo` command represents a new line. That character should be interpreted by the `echo` command and the generated file should not contain the literal `\n` and should contain a new line. This means the file `/tmp/wazuh_envs` should take 2 lines:
- 1 that defines the environment variables
- 1 blank/empty line
