### ISSUE TITLE
Adapt the new menu of Opensearch Dashboard 2.16.0

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-dashboard-plugins#6939]
**Description**

In version 2.16.0 a new menu is added that is configured by the setting home:useNewHomePage, which has its method to register the applications in that menu, we would have to register the applications to be seen as we want in the new menu.

**Preconditions**
1.  Use 2.16.0

**Steps to reproduce**
1. Navigate to 'Dashboards managements>Advanced settings'
2. Search for the configuration 'Use New Home Page' and activate it
3. See the side menu

**Expected Result**

That the applications are separated as in the previous menu.

**Actual Result**

![image](https://github.com/user-attachments/assets/518b9841-4dc7-40e3-9d96-4eab7f9fe870)

**Comment by yenienserrano** [comment]
we have seen some issues with the implementation of the new menu as it is in testing phase

In the menu all the added categories have the `See all...` button even if it shows you all the applications or only 1.

![image](https://github.com/user-attachments/assets/51ac940b-2427-4afb-9ca9-a950c97dab64)

at small screen sizes the application becomes unusable because an overlay is put in place

![image](https://github.com/user-attachments/assets/8056c580-753e-43fd-8383-a57d153e61fb)

We would have to make quite a few changes at the fork because they have many routes home coded, for example. That in the future they could change by configuration.

![image](https://github.com/user-attachments/assets/b42d2d99-340c-4efd-85a6-a0e05a88e3ec)

**Comment by asteriscos** [comment]
We will not implement the new OpenSearch menu yet, because we found some buggy behavior in the native features.
