### ISSUE TITLE
Release 4.9.0 - Release candidate 1 - Wazuh UI regression testing

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6942]
The following issue aims to run manual tests for the current release candidate, report the results, and open new issues for any encountered errors.

## Wazuh UI tests information
|                                        |     |
|----------------------------------------|-----|
| **Main release candidate issue**       |  https://github.com/wazuh/wazuh/issues/25332   |
| **Version**                            |   4.9.0  |
| **Release candidate #**                |  RC 1  |
| **Tag**                                |  [v4.9.0-rc1](https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v4.9.0-rc1)   |
| **Previous UI regression tests issue** |   https://github.com/wazuh/wazuh-dashboard-plugins/issues/6897  |

## Test report procedure

**TL;DR**
   1. The specified tests will be executed in every platform and version mentioned in this issue.
   1. Include evidence of each test performed.
   1. Report any problem or bug. Open a new issue for each of them and link them here.
   1. Justify skipped tests.

All test results must have one the following statuses: 
|                 |                                                                      |
|-----------------|----------------------------------------------------------------------|
| :black_circle:  | The test hasn't started yet.                                         |
| :green_circle:  | All checks passed.                                                   |
| :red_circle:    | There is at least one failed check.                                  |
| :yellow_circle: | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause.
It must be included in the `Problems` section of the current release candidate issue.

Any expected fail or skipped test must be justified with a reason. 
All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip, txt or images. 
This report can be used by the auditors to dig deeper into any possible failures and details.

## Test

| Test                                                                 | Chrome         | Firefox        | Safari         |
|---------------------------------------------------------------------|----------------|----------------|----------------|
| Verify the app package installs and operates as expected | :green_circle:   | :green_circle: | :green_circle: |
| Use absolute date range on change page requests (#6923) | :green_circle:  | :green_circle: | :green_circle: |
| Sync initial filters with app state (#6927) | :green_circle:  | :green_circle: | :green_circle: |
| Fix events data table pagination exception (#6917) | :green_circle:  | :green_circle: | :green_circle: |
| Add default sorting and columns in all data grid tables (#6912) | :green_circle:  | :green_circle: | :green_circle: |
| Fix error generating dashboard reports on Firefox (#6902) | :green_circle:  | :green_circle: | :green_circle: |

## Test plan

1. Verify the app package installs and operates as expected.
2. [Use absolute date range on change page requests](https://github.com/wazuh/wazuh-dashboard-plugins/pull/6923)
3. [Sync initial filters with app state](https://github.com/wazuh/wazuh-dashboard-plugins/pull/6927)
4. [Fix events data table pagination exception](https://github.com/wazuh/wazuh-dashboard-plugins/pull/6917)
5. [Add default sorting and columns in all data grid tables](https://github.com/wazuh/wazuh-dashboard-plugins/pull/6912)
6. [Fix error generating dashboard reports on Firefox](https://github.com/wazuh/wazuh-dashboard-plugins/pull/6902)

## Conclusions :green_circle:

Tests were performed successfully.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @asteriscos

**Comment by Tostti** [comment]
## Test

| Test                                                                 | Chrome         | Firefox        | Safari         |
|---------------------------------------------------------------------|----------------|----------------|----------------|
| Verify the app package installs and operates as expected | :green_circle:   | :black_circle: | :black_circle: |
| Use absolute date range on change page requests (#6923) | :green_circle:  | :black_circle: | :black_circle: |
| Sync initial filters with app state (#6927) | :green_circle:  | :black_circle: | :black_circle: |
| Fix events data table pagination exception (#6917) | :green_circle:  | :black_circle: | :black_circle: |
| Add default sorting and columns in all data grid tables (#6912) | :green_circle:  | :black_circle: | :black_circle: |
| Fix error generating dashboard reports on Firefox (#6902) | :green_circle:  | :black_circle: | :black_circle: |


<details>
<summary>Verify the app package installs and operates as expected.</summary>

### Chrome
![image](https://github.com/user-attachments/assets/4267a3bb-8794-4c8c-a4f5-67e13b207d38)
![image](https://github.com/user-attachments/assets/7920c155-7589-499b-a050-55c6a051a5a8)
![image](https://github.com/user-attachments/assets/628a8ecc-20c2-48a0-b55a-c90a4baef54c)

### Firefox

### Safari

</details>

<details>
<summary>Use absolute date range on change page requests</summary>

### Chrome

https://github.com/user-attachments/assets/954dc60c-d377-491f-b9d4-9fe877c5228f



### Firefox

### Safari

</details>

<details>
<summary>Sync initial filters with app state</summary>

### Chrome

https://github.com/user-attachments/assets/fb9baf53-8e95-42e3-83ee-c0432c09839a



### Firefox

### Safari

</details>

<details>
<summary>Fix events data table pagination exception</summary>

### Chrome

https://github.com/user-attachments/assets/718060ce-ffeb-4faa-8487-43bdb9ce38d9



### Firefox

### Safari

</details>

<details>
<summary>Add default sorting and columns in all data grid tables</summary>

### Chrome

https://github.com/user-attachments/assets/0673553b-bf97-4de9-8f0f-3cac24d3e395



### Firefox

### Safari

</details>

<details>
<summary>Fix error generating dashboard reports on Firefox</summary>

### Chrome
![image](https://github.com/user-attachments/assets/5d41d88a-5914-4731-be0f-c5d211d6f2c0)

### Firefox

### Safari

</details>

**Comment by asteriscos** [comment]
Tests look good to me :green_circle:
