### ISSUE TITLE
Elastic 8.15 integration dashboard incompatibility

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6958]
# Description

It's been reported a problem on the `wazuh-amazon-aws-v1.0` integration dashboard for ElasticSearch 8.15. The Events visualization doesn't seem to be showing any information when it should. We need to check this and see if we need to make any modifications to the dashboard

Related issue:
- https://github.com/wazuh/wazuh-indexer/issues/367

**Screenshots**
![image](https://github.com/user-attachments/assets/dc097b7a-0277-4a11-9417-fac5666172b8)

**Comment by chantal-kelm** [comment]
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/e35db52a-24b8-469e-af34-154ce4a61e21">

<img width="1792" alt="image" src="https://github.com/user-attachments/assets/f42d3927-5aac-49a4-9d54-87a5bc75e869">

**Comment by asteriscos** [comment]
I will close this as not planned because the dashboard works properly.
