### ISSUE TITLE
A custom style truncates Discover plugin rows

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6976]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 07 | Chrome, Firefox, Safari, etc |

# Description

It seems there's a custom style truncating the Discover plugin rows. We need to identify why it's there in the first place and fix it, so it doesn't affect the Discover plugin.

Related code:
https://github.com/wazuh/wazuh-dashboard-plugins/blob/v4.9.0/plugins/main/public/styles/layout.scss#L383

**Expected Result**

![image](https://github.com/user-attachments/assets/d1307cca-e233-4c06-8a84-41d5afab5834)

**Actual Result**

![image](https://github.com/user-attachments/assets/c3d666ac-34d7-416d-bb97-0e6df2e344af)

**Comment by Desvelao** [comment]
The `font-size` style was changed in https://github.com/wazuh/wazuh-dashboard-plugins/commit/170aeabee1d422924d7f4f284b95be3df2c3f2af related to https://github.com/wazuh/wazuh-dashboard-plugins/pull/1827.

The rest of styles related to `.table` class, were added in https://github.com/wazuh/wazuh-dashboard-plugins/commit/b0cbf62e8a6bc9a85a51ceae35ca4e46d28d416d

By the message of commit, it is not clear the reason. I was researching and I did not find the code could be present before.

It seems the commit could be introduced to the Wazuh app for Kibana [v3.9.1-7.1.0](https://github.com/wazuh/wazuh-dashboard-plugins/releases/tag/v3.9.1-7.1.0). For the Wazuh app 3.9.1 threre are tags:
- v3.9.1-7.1.1
- v3.9.1-7.1.0
- v3.9.1-6.8.0
- v3.9.1-6.7.2

The style definition exists in:
- v3.9.1-7.1.1
- v3.9.1-7.1.0

so, this change could be related to the Kibana version.

**Comment by Tostti** [comment]
# Research

The following elements will be affected if the style is removed: 

## Flyouts 
### Before
![image](https://github.com/user-attachments/assets/cdd10872-94fa-44e1-b273-abe92bac9115)

### After
![image](https://github.com/user-attachments/assets/cb03152e-569c-44bd-8dca-3b03d8b88301)

## Discover
### Before 
![image](https://github.com/user-attachments/assets/c2fbd5f7-b1f3-4ae9-9bf8-bc84ec294a6a)

### After
![image](https://github.com/user-attachments/assets/3abdd7fd-2a33-46c1-bf45-4e22730e3bd6)


It is safe to remove the style, to remain consistent with OpenSearch styling. 

# Additional discover
Removing the custom style prevents the truncation of the row from being visible. However, it is still truncated a little bit. This also happens in[ OpenSearch ](https://playground.opensearch.org/app/data-explorer/discover). 

![image](https://github.com/user-attachments/assets/f05df837-bccd-47e6-aa57-6b856b30858b)

The origin is the class `truncate-by-height`, which limits the maximum height to a specific value of 115px. If that value was increased by 3px, there will be no truncation:
![image](https://github.com/user-attachments/assets/e314d34b-1e7e-4b3b-9c9e-78da4e652803)
