### ISSUE TITLE
Vulnerability dashboard error loading for read-only user

### ISSUE THREAD

**Issue by TDYK** [wazuh/wazuh-dashboard-plugins#6985]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0-1| ubuntu-rep| any |

**Description**
Vulnerability dashboard not working for read-only user

**Preconditions**
Wazuh Installation from repository on Ubuntu 20.04

**Steps to reproduce**
1. Create a read-only user as discribed in https://documentation.wazuh.com/current/user-manual/user-administration/rbac.html
2. Login with new read-only user and navigate to app/vulnerability-detection
3. The page is not loading 

Error in logs:
```
[2024-09-10T14:02:19,459][WARN ][o.o.s.c.PrivilegesInterceptorImpl] [Wazuh-Indexer-01P] Tenant global_tenant is not allowed to write (user: readonly)
[2024-09-10T14:02:19,620][WARN ][o.o.s.c.PrivilegesInterceptorImpl] [Wazuh-Indexer-01P] Tenant global_tenant is not allowed to write (user: readonly)
```
Error in browser console:
```
PUT
https://wazuh/api/saved_objects/index-pattern/wazuh-states-vulnerabilities-*
[HTTP/2 403  25ms]
```
**Screenshots**
![image](https://github.com/user-attachments/assets/f16c2c8d-a76a-49c5-920d-48067b26358e)

Other pages that work with index are working, like this:
![image](https://github.com/user-attachments/assets/e10c59a1-f030-40de-ad87-e3f4db88a466)

**Comment by TDYK** [comment]
Same issue in the mailing list:
https://groups.google.com/g/wazuh/c/_w_BNaohbzE

**Comment by Desvelao** [comment]
I got to replicate the problem.

1. Create a readonly user following these steps https://documentation.wazuh.com/4.9/user-manual/user-administration/rbac.html
2. Ensure the Vulnerabilities detection in the Wazuh server is enabled and this can connect with the Wazuh indexer
3. Ensure the vulnerabilities states index was created
4. With a user with write permission on the selected tenant, go to Vulnerabilities Detection > Dashboard / Inventory, and it should create the index pattern
5. Create the read only user following the steps https://documentation.wazuh.com/4.9/user-manual/user-administration/rbac.html
6. Login with the read only user and go to Vulnerabilities Detection > Dashboard / Inventory.

The view is stucked in the `Searching`:
![image](https://github.com/user-attachments/assets/72ac3393-72f9-4e39-9cc4-41d49e505b99)

Regarding the request from the browser dev tools, there are some requests failing

![image](https://github.com/user-attachments/assets/e567b71e-9ca4-4af6-921e-3b3544028920)
![image](https://github.com/user-attachments/assets/b50ad59c-48e8-478c-a626-2fb5b7bff62a)


```
{
    "statusCode": 403,
    "error": "Forbidden",
    "message": "no permissions for [indices:data/write/update] and User [name=wz-readonly, backend_roles=[], requestedTenant=null]: security_exception: [security_exception] Reason: no permissions for [indices:data/write/update] and User [name=wz-readonly, backend_roles=[], requestedTenant=null]"
}
```

This indicates and error trying to update the index pattern. Regarding the initiator of this request, this seems to be related the `select` method of the data source that is updating the index pattern data. This action can not be done by read only users.

Related code: https://github.com/wazuh/wazuh-dashboard-plugins/blob/v4.9.0/plugins/main/public/components/common/data-source/pattern/pattern-data-source.ts#L55

For another hand, going to `Events` tab, this is displayed, so I assume, the `select` method of the data source is not called.

This is a bug.
