### ISSUE TITLE
AWS Integration - Problem with comma separated values

### ISSUE THREAD

**Issue by R00G3R** [wazuh/wazuh-dashboard-plugins#7008]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-rev | Wazuh Dashboard| Manager | Packages| CentOS 7|

Hi folks,

I started using the AWS integration and noticed the field with multiple values separated by comma is not showing on the dashboard when it enables the respective field filter.

![image](https://github.com/user-attachments/assets/3e249ac4-b80d-4ccf-82f3-0bc5bb96e49c)
 
 This is what show when you inspect the event.

![image](https://github.com/user-attachments/assets/234e1080-a6aa-4535-82fd-2333a9109177)

**Comment by guidomodarelli** [comment]
# v 4.10.0
## Brave [Version 1.70.119 Chromium: 129.0.6668.70 (Official Build) (64-bit)](https://brave.com/latest/)
![image](https://github.com/user-attachments/assets/b1369459-6eda-4384-90be-ec6b334e4384)

**Comment by guidomodarelli** [comment]
Fixed on https://github.com/wazuh/wazuh-dashboard-plugins/blob/930e5d57ebacb77d511c8387b2598926eb0dcc34/plugins/main/public/components/common/data-grid/use-data-grid.tsx#L167-L178
![image](https://github.com/user-attachments/assets/230a808f-9699-4e08-816c-885f21d7d9eb)

![image](https://github.com/user-attachments/assets/5d42b411-89e3-4daf-9a64-58e2756d14ca)
