### ISSUE TITLE
Document details flyout column text overflow

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#7039]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 07 | Chrome, Firefox, Safari, etc |

**Description**
Whenever a field is too long it overflows the Document details flyout column.

**Screenshots**
![image](https://github.com/user-attachments/assets/3c0667d6-9549-4ea2-9466-ecb14a55ce3c)

**Comment by guidomodarelli** [comment]
# v 4.9.0
## Brave
![image](https://github.com/user-attachments/assets/23fa0ad1-1ceb-4ce1-a19b-f50b14a47fea)

## Firefox Developer Edition
![image](https://github.com/user-attachments/assets/a70ffb4b-5489-4528-88c8-df7be948894a)

# Edge
![image](https://github.com/user-attachments/assets/f6177f6b-6925-4c34-970e-3082415cccd2)
