### ISSUE TITLE
Timeout error when exporting CSV in FIM

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh-dashboard-plugins#7068]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.1 | xyzw | Chrome, Firefox, Safari, etc |

**Description**

Timeout error when exporting CSV in FIM

**Screenshots**

https://github.com/user-attachments/assets/cffbc185-574f-4f55-b6b9-7842e25a8533

**Comment by JuanGarriuz** [comment]
Adding a lot of timeout the response stop on 4 min.

![image](https://github.com/user-attachments/assets/65add1a8-6c76-4240-b7cc-01e456c8fb88)

**Comment by JuanGarriuz** [comment]
### 70K Files

![image](https://github.com/user-attachments/assets/8584f6bc-ac61-4724-a742-4d1134498636)
