### ISSUE TITLE
Improve available columns filter performance

### ISSUE THREAD

**Issue by guidomodarelli** [wazuh/wazuh-dashboard-plugins#7073]
### Description

Improve available columns filter performance

![Image](https://github.com/user-attachments/assets/60bce51d-14d7-443f-8a69-4753750f903d)

**Comment by guidomodarelli** [comment]
![image](https://github.com/user-attachments/assets/45707693-7a8e-4f7f-869a-f1e4ea0a11e8)

![image](https://github.com/user-attachments/assets/f38c2353-26ec-4c27-b003-90513cf96520)

https://github.com/user-attachments/assets/178978d2-fbeb-4cd8-8a44-fed64f3dabc6

**Comment by JuanGarriuz** [comment]
Hardcoding the column values instead of using useMemo does not affect the response time of the popover loading.

https://github.com/user-attachments/assets/2ce5d4ef-f539-4437-8cae-15d1b8aa9082

Additionally, I’ll link to the Datagrid documentation.

https://oui.opensearch.org/1.5/#/tabular-content/data-grid

**Comment by Desvelao** [comment]
Reducing the count of columns to display in the columns selector enhances the performance of the component rendering.

For another hand, and as last option, the EuiDataGrid component allows to disable the visibility of default columns selector and allows the addition of controls. This could allow creating a custom columns selector and see if this enhances the performance.

**Comment by asteriscos** [comment]
I will close this issue as the analysis provided no relevant way to improve the performance of the component.

**Comment by asteriscos** [comment]
OpenSearch upgraded the DomPurify dependency which improves the performance of the data-grid component. This change was implemented in OS 2.14.0, therefore Wazuh 4.10.0 should benefit from this.
- https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6599
