### ISSUE TITLE
FIM flyout filters not working

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#7082]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 07 | Chrome, Firefox, Safari, etc |

**Description**
When a user clicks on the filters located in the File Integrity Monitoring / Inventory flyout nothing happens. These filters should trigger the filtering of the value in the main (background) table.

**Screenshots**

![Peek 2024-10-08 13-13](https://github.com/user-attachments/assets/b2428125-6ef8-4526-be90-e0f56a08ef46)

**Comment by Desvelao** [comment]
I fixed the ability to filter from Files details flyout and add some enhancements, see https://github.com/wazuh/wazuh-dashboard-plugins/pull/7119
