### ISSUE TITLE
Improve loading speed

### ISSUE THREAD

**Issue by guidomodarelli** [wazuh/wazuh-dashboard-plugins#7084]
# Description

The primary objective is to enhance the application's initial load time.

![image](https://github.com/user-attachments/assets/60ab98ea-a085-4315-b2e1-8e8b77b75628)

**Comment by guidomodarelli** [comment]
![image](https://github.com/user-attachments/assets/22b78b98-a96b-49e5-b575-db223739c019)
In this last change, I thought that using `Promise.allSettled` would improve something, but it didn't.
![image](https://github.com/user-attachments/assets/15e5c992-f46f-41b8-8d23-5a060ec4c37f)

**Comment by guidomodarelli** [comment]
#### `/login`

![image](https://github.com/user-attachments/assets/b1d39a22-1160-4fbe-8333-02aca1671dce)

<details><summary>BEFORE</summary>
<br />
  Average of 109,625 ms

  ![image](https://github.com/user-attachments/assets/27acc420-9c75-472f-b969-a1a276b9c226)

</details>

<details><summary>AFTER</summary>
<br />
  Average of 507,25 ms

  ![image](https://github.com/user-attachments/assets/2bf4fd70-3b55-4de8-a1b8-e79f181cdecc)

</details>

**Comment by asteriscos** [comment]
The proposed changes don't provide a substantial improvement in the loading speed, therefore I will close this issue. We will re-visit this topic in the future.
