### ISSUE TITLE
Change loading logo size

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard-plugins#7102]
# Description

We want to decrease the loading logo a 30%.

<img width="670" alt="image" src="https://github.com/user-attachments/assets/545a58a2-d95e-4d96-9dee-b9abcc8ee86b">

**Comment by Desvelao** [comment]
Reduced the size of the loading logo from 150px to 100px here: https://github.com/wazuh/wazuh-dashboard/pull/373
