### ISSUE TITLE
Design the inventory ribbon as the dashboard one

### ISSUE THREAD

**Issue by guidomodarelli** [wazuh/wazuh-dashboard-plugins#7123]
# Description
Design the inventory ribbon as the dashboard one

From this design:

<img width="1489" alt="image" src="https://github.com/user-attachments/assets/c05a3b8a-398a-4bdb-a692-f2ff95623310">

To this one:

<img width="1496" alt="image" src="https://github.com/user-attachments/assets/8e331f1d-b8ab-4914-995e-db2f8f4f8119">

**Comment by asteriscos** [comment]
I'm closing this issue because it will be done in:
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7111
