### ISSUE TITLE
Search bar related to Wazuh server data does not display the external filters when reapplied

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-dashboard-plugins#7124]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.10.x | xyzw | Chrome, Firefox, Safari, etc |

**Description**
The search bar of tables related to the Wazuh server could not display the filters that were applied externally. See the `Steps to reproduce` for more information about the use case.
> TableWzAPI component

**Steps to reproduce**
1. Apply an external filter
2. Use the search bar to apply a new filter
3. Apply the same external filter of step 1 (using the external interaction, do not use the search bar)

https://github.com/user-attachments/assets/b25eb968-ea2a-44a9-a15a-f05fc15793c5

**Expected Result**
1. The search bar should display the current filter applied

**Actual Result**
1. The search bar does not display the current filter applied in the commented use case

**Comment by JuanGarriuz** [comment]
### Research

`input` is correctly set to the filter we added the first time

![image](https://github.com/user-attachments/assets/dbf6bda5-6507-41ad-8330-f399b2497e22)

When clear the search-bar `input` work as expected

![image](https://github.com/user-attachments/assets/71f81ddd-3ad1-4667-8a7e-906268f796a7)

2º time it fail

![image](https://github.com/user-attachments/assets/94fa76c9-6dd9-4541-8d05-86d3397cbaf1)

**Comment by JuanGarriuz** [comment]
### Update 02/12

In charge `rest.input` render on `SearchBar `component has no value.

![image](https://github.com/user-attachments/assets/aba75adf-0705-46b5-804b-1015c5838baa)

On filter added `rest,input` work correctly, changes to ethe xpected value filter.

![image](https://github.com/user-attachments/assets/71d41f69-7c63-4f96-a52c-61fbc24e9a4f)

When I delete the filter on search-bar this code tracks the new filter, but `rest.input `are not managed:

```
  // Handler on change the input field text
  const onChangeInput = event => setInput(event.target.value);
```

![image](https://github.com/user-attachments/assets/6d526923-09cb-4e8e-baf5-87156f96024b)

It means that the `useEffect` that we are using doesn't get the conditional requirements to run up. When the `rest.input` doesn't change it can't do anything.

```
  useEffect(() => {
    var _searchBarQueryLangua3, _searchBarQueryLangua4, _searchBarQueryLangua5;
    // React to external changes and set the internal input text. Use the `transformInput` of
    // the query language in use
    rest.input && ((_searchBarQueryLangua3 = searchBarQueryLanguages[queryLanguage.id]) === null || _searchBarQueryLangua3 === void 0 ? void 0 : _searchBarQueryLangua3.transformInput) && setInput((_searchBarQueryLangua4 = searchBarQueryLanguages[queryLanguage.id]) === null || _searchBarQueryLangua4 === void 0 || (_searchBarQueryLangua5 = _searchBarQueryLangua4.transformInput) === null || _searchBarQueryLangua5 === void 0 ? void 0 : _searchBarQueryLangua5.call(_searchBarQueryLangua4, rest.input, {
      configuration: queryLanguage.configuration,
      parameters: selectedQueryLanguageParameters
    }));
  }, [rest.input]);
```

![image](https://github.com/user-attachments/assets/7ef112c7-2861-4634-be1e-d49a4cc36012)
