### ISSUE TITLE
Statistics analysis engine dashboard queue usage is misleading

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#7181]
## Description
Currently, the analysis engine queue usage visualizations display not only the absolute value of the amount of decoded events, but also shows the queue usage percentages. Using the same visualization to display both values has proven to be misleading, therefore we have to design and propose a better and easier-to-understand way to show the percentages of the events queue usage.

![image](https://github.com/user-attachments/assets/ef6d0b26-7e94-4029-864b-e61802766dab)

## Tasks

- [ ] Redesign queue usage statistics visualizations

**Comment by guidomodarelli** [comment]
I have looked into the issue and analyzed the problem. I am unclear about what the term '[syscheck_queue_usage](https://documentation.wazuh.com/current/user-manual/manager/wazuh-server-queue.html#:~:text=syscheck_queue_usage%3D'0.00')' signifies.
