### ISSUE TITLE
Expand the command column in the Processes table

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#7194]
# Description

We want to allow the command column to expand as much as possible. To achieve this we have to move the column to the right-most position.

## Task

- [x] Move the Command column to the right-most position.

  ![image](https://github.com/user-attachments/assets/d7dbfbd3-999b-4cd1-83cf-92258ebcb928)

**Comment by chantal-kelm** [comment]
<img width="1792" alt="Captura de pantalla 2024-12-09 a la(s) 10 55 47 a  m" src="https://github.com/user-attachments/assets/7397d19d-6cd5-4519-8807-cc071c15c87f">

<img width="1792" alt="Captura de pantalla 2024-12-09 a la(s) 10 56 39 a  m" src="https://github.com/user-attachments/assets/b15508a1-c8fa-4fe1-813d-dae61d5bec28">

**Comment by chantal-kelm** [comment]
It was decided to expand the command column, relocate the argvs column and change the width of the rest of the processes table columns.

<img width="1792" alt="image" src="https://github.com/user-attachments/assets/6a0d4ae0-612b-4b57-92cf-e5a861e0d2ec">
