### ISSUE TITLE
ERROR3099 - Server not ready yet,    Managing multiple Wazuh clusters with Cross-Cluster Search

### ISSUE THREAD

**Issue by viaHem** [wazuh/wazuh-dashboard-plugins#7197]
I am setting up a new test environment via "Managing multiple Wazuh clusters with Cross-Cluster Search"
But doing this gives me for the 4th time this error: returnErrorInstance@https://192.168.1.143/49201/bundles/plugin/wazuh/wazuh.plugin.js:1:532977
checkApi@https://192.168.1.143/49201/bundles/plugin/wazuh/wazuh.plugin.js:1:532689

<img width="1440" alt="Scherm­afbeelding 2024-12-07 om 11 41 27" src="https://github.com/user-attachments/assets/1f592f2e-2ec7-409e-8485-efbfe9f40c34">

The setup is now in one network, the (ubuntu) servers are 192.168.1.143 (css-indexer-1 and dashboard) 192.168.1.153 (ca-inderxer-1) and 192.168.1.137 (ca-server-1)
The installation manual is written for wazuh 4.8.2, but I've seen that parts were installed as 4.9.x  

Does anyone understand what I am doing wrong?

**Comment by yenienserrano** [comment]
Hi @viaHem, i understand that you can't connect to the Wazuh server, it could be that the configuration in the `wazuh.yml` of the manager is not set correctly, can you check it?

You can also check the logs to see if there is any problem.

```console
cat /var/log/filebeat/filebeat | grep -i -E "error|warn"
cat /var/ossec/logs/ossec.log | grep -i -E "error|warn"
```

I also share with you the link to the documentation where you can see other tests that you can make

https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/troubleshooting.html#troubleshooting

**Comment by viaHem** [comment]
Dear Ian,

My wazuh.yml on the wazuh-dashboard server looks like this;
hosts:
  - Cluster A:
      url: https://192.168.1.137
      port: 55000
      username: wazuh
      password: wazuh
      run_as: true

The ip-address is correct for the wazuh-server in cluster A, I am not sure about the username I've seen 4 different versions of it like: wazuh, wazuh-wui, foo and admin. But with this wazuh user I get one error less.   

Another strange thing is when I followed the manual: https://wazuh.com/blog/managing-multiple-wazuh-clusters-with-cross-cluster-search/   the manual shows port 9200 and 9300? In the second setup I only used port 9200.

When I try to nmap -p0 192.168.1.143 (from the ca-wazuh-server to the  ccs-dashboard-server) port 55000 is not open.

And from the logfiles I get the information that the disk is full. I tried to delete some files but it keeps filling up, 
2024/12/17 06:43:35 wazuh-db: ERROR: SQLite: database or disk is full
2024/12/17 06:43:35 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscollector
2024/12/17 06:43:35 wazuh-db: ERROR: SQLite: database or disk is full
2024/12/17 06:43:35 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscollector
2024/12/17 06:43:35 wazuh-db: ERROR: SQLite: database or disk is ful2024/12/17 13:47:17 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.

root@ca-wazuh-server-1:/home/rabbit# df -h
Filesystem                         Size  Used Avail Use% Mounted on
tmpfs                              392M  688K  391M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   15G   15G     0 100% /
tmpfs                              2.0G   80K  2.0G   1% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
/dev/sda2                          2.0G   94M  1.7G   6% /boot
tmpfs                              392M   12K  392M   1% /run/user/1000


root@ca-wazuh-server-1:/var/ossec/queue/vd# sudo du -cha --max-depth=1 /var/ossec/queue/vd | grep -E "M|G"
4.1M	/var/ossec/queue/vd/event
4.1M	/var/ossec/queue/vd/delayed
5.5G	/var/ossec/queue/vd/feed
4.1M	/var/ossec/queue/vd/reports
4.1M	/var/ossec/queue/vd/inventory
5.5G	/var/ossec/queue/vd
5.5G	total
root@ca-wazuh-server-1:/var/ossec/queue/vd# cd feed
root@ca-wazuh-server-1:/var/ossec/queue/vd/feed# ls
000092.log  000409.sst  000762.sst  001223.sst  001605.sst  001731.sst
000127.sst  000413.sst  000765.sst  001224.sst  001606.sst  001732.sst
000131.sst  000414.sst  000775.sst  001244.sst  001609.sst  001733.sst
000135.sst  000417.sst  000776.sst  001246.sst  001610.sst  001735.sst
000140.sst  000420.sst  000793.sst  001250.sst  001615.sst  001736.sst
000144.sst  000424.sst  000801.sst  001251.sst  001620.sst  001737.sst
000146.sst  000431.sst  000805.sst  001312.sst  001621.sst  001738.sst
000148.sst  000438.sst  000811.sst  001313.sst  001624.sst  001740.sst
000151.sst  000441.sst  000824.sst  001314.sst  001628.sst  001741.sst
000152.sst  000445.sst  000827.sst  001325.sst  001631.sst  001742.sst
000153.sst  000450.sst  000829.sst  001329.sst  001632.sst  001743.sst
000155.sst  000457.sst  000840.sst  001386.sst  001633.sst  001744.sst
000157.sst  000463.sst  000845.sst  001389.sst  001634.sst  001745.sst
000159.sst  000464.sst  000864.sst  001390.sst  001641.sst  001746.sst
000162.sst  000467.sst  000865.sst  001439.sst  001643.sst  001749.sst
000166.sst  000471.sst  000867.sst  001440.sst  001646.sst  001750.sst
000168.sst  000482.sst  000869.sst  001447.sst  001647.sst  001751.sst
000170.sst  000484.sst  000874.sst  001448.sst  001648.sst  001752.sst
000172.sst  000492.sst  000875.sst  001478.sst  001653.sst  001754.sst
000174.sst  000496.sst  000889.sst  001479.sst  001654.sst  001759.sst
000176.sst  000501.sst  000890.sst  001480.sst  001655.sst  001761.sst
000178.sst  000508.sst  000897.sst  001481.sst  001656.sst  001762.sst
000181.sst  000523.sst  000899.sst  001482.sst  001658.sst  001763.sst
000182.sst  000531.sst  000902.sst  001487.sst  001659.sst  001765.sst
000185.sst  000535.sst  000905.sst  001488.sst  001660.sst  001766.sst
000195.sst  000536.sst  000907.sst  001503.sst  001662.sst  001767.sst
000205.sst  000538.sst  000930.sst  001505.sst  001663.sst  001768.sst
000211.sst  000544.sst  000938.sst  001508.sst  001666.sst  001769.sst
000212.sst  000559.sst  000940.sst  001509.sst  001667.sst  001770.sst
000214.sst  000561.sst  000941.sst  001510.sst  001669.sst  001771.sst
000225.sst  000565.sst  000946.sst  001511.sst  001670.sst  001772.sst
000226.sst  000567.sst  000947.sst  001513.sst  001672.sst  001774.sst
000231.sst  000569.sst  000948.sst  001521.sst  001675.sst  001775.sst
000235.sst  000580.sst  000951.sst  001525.sst  001676.sst  001776.sst
000241.sst  000585.sst  000952.sst  001527.sst  001678.sst  001777.sst
000245.sst  000593.sst  000958.sst  001531.sst  001679.sst  001778.sst
000250.sst  000600.sst  000963.sst  001533.sst  001682.sst  001779.sst
000252.sst  000605.sst  000968.sst  001535.sst  001684.sst  001780.sst
000254.sst  000607.sst  000971.sst  001538.sst  001685.sst  001781.sst
000262.sst  000615.sst  000977.sst  001539.sst  001686.sst  001782.sst
000267.sst  000616.sst  000992.sst  001541.sst  001688.sst  001783.sst
000268.sst  000617.sst  000997.sst  001542.sst  001689.sst  001784.sst
000271.sst  000620.sst  001005.sst  001543.sst  001691.sst  001785.sst
000272.sst  000624.sst  001018.sst  001553.sst  001694.sst  001789.sst
000275.sst  000625.sst  001026.sst  001554.sst  001696.sst  001790.sst
000278.sst  000630.sst  001033.sst  001558.sst  001698.sst  001791.sst
000282.sst  000634.sst  001041.sst  001559.sst  001700.sst  001792.sst
000286.sst  000635.sst  001046.sst  001560.sst  001701.sst  001793.sst
000288.sst  000645.sst  001073.sst  001561.sst  001703.sst  001795.sst
000297.sst  000653.sst  001074.sst  001564.sst  001706.sst  001797.sst
000298.sst  000659.sst  001076.sst  001567.sst  001707.sst  001799.sst
000304.sst  000671.sst  001094.sst  001568.sst  001708.sst  001800.sst
000308.sst  000676.sst  001111.sst  001569.sst  001709.sst  001802.sst
000309.sst  000685.sst  001117.sst  001571.sst  001711.sst  001803.sst
000330.sst  000687.sst  001129.sst  001572.sst  001715.sst  001805.sst
000348.sst  000696.sst  001138.sst  001573.sst  001716.sst  001806.sst
000352.sst  000697.sst  001139.sst  001574.sst  001717.sst  001808.sst
000354.sst  000700.sst  001143.sst  001575.sst  001718.sst  CURRENT
000355.sst  000707.sst  001157.sst  001581.sst  001719.sst  IDENTITY
000360.sst  000708.sst  001168.sst  001587.sst  001720.sst  LOCK
000362.sst  000715.sst  001180.sst  001590.sst  001721.sst  LOG
000364.sst  000717.sst  001181.sst  001592.sst  001722.sst  MANIFEST-000005
000374.sst  000727.sst  001187.sst  001593.sst  001723.sst  OPTIONS-000217
000385.sst  000733.sst  001198.sst  001595.sst  001725.sst  OPTIONS-000219
000392.sst  000734.sst  001199.sst  001599.sst  001727.sst
000394.sst  000735.sst  001207.sst  001601.sst  001728.sst
000397.sst  000736.sst  001208.sst  001603.sst  001729.sst
root@ca-wazuh-server-1:/var/ossec/queue/vd/feed# rm 00*.sst
root@ca-wazuh-server-1:/var/ossec/queue/vd/feed# ls
000092.log  IDENTITY  LOG              OPTIONS-000217
CURRENT     LOCK      MANIFEST-000005  OPTIONS-000219


root@ca-wazuh-server-1:/home/rabbit# df -h
Filesystem                         Size  Used Avail Use% Mounted on
tmpfs                              392M  696K  391M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   15G  9.3G  4.7G  67% /
tmpfs                              2.0G     0  2.0G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
/dev/sda2                          2.0G   94M  1.7G   6% /boot
tmpfs                              392M   12K  392M   1% /run/user/1000



But within 30 minutes the disk is full again....

Please advice what I did wrong, 

Kind regards,
Erick.

**Comment by viaHem** [comment]
Sorry wrong way around, I tested communication from ccs-dashboard-server to ca-wazuh-server....

root@ccs-wazuh-master:/home/rabbit# curl -k -X GET "https://192.168.1.137:55000/" -H "Authorization: Bearer $(curl -u wazuh:wazuh -k -X POST 'https://192.168.1.137:55000/security/user/authen-wuiticate?raw=true')"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    50  100    50    0     0   4195      0 --:--:-- --:--:-- --:--:--  4545
{"title": "Unauthorized", "detail": "Invalid token"}root@ccs-wazuh-master:/home/rabbit# 

I can send you the complete CLI cmd script how I installed the 3 servers if that helps (-;

regards, Erick.

**Comment by yenienserrano** [comment]
If it must be a problem with the username and password you are using, 

You can try with the user wazuh-wui and password wazuh-wui if it doesn't work you will have to search or change the password if you don't know it.

If you did a step-by-step installation and also did that step then the passwords were changed.
https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/step-by-step.html#securing-your-wazuh-installation

If you have the file wazuh-install-files.tar you can recover the passwords with the following command
`tar -axf wazuh-install-files.tar wazuh-install-files/wazuh-passwords.txt -O | grep -P "\'wazuh-wui\'" -A 1`

If you don't have it you can try changing the passwords as the documentation says.
https://documentation.wazuh.com/current/user-manual/user-administration/password-management.html

**Comment by yenienserrano** [comment]
I close due to inactivity

**Comment by viaHem** [comment]
> Dear Ian Yenien Serrano

Thanks for helping me out, the server is functioning now. The reason I reacted so late is because of my health (I was a little bit ill) but once again thanks for helping me out.

Kind regards,
Met vriendelijke groet,

Erick Hemmen

￼

M: +31 6 11 3 22 77 8
E: ***@***.***

Deze e-mail (met eventuele bijlagen) is uitsluitend bestemd voor de beoogde geadresseerde(n). Als deze e-mail niet aan u is gericht, dan vragen wij u om de afzender daarvan op de hoogte te stellen en deze e-mail te wissen. Het is niet toegestaan om deze e-mail openbaar te maken, er derden kennis van te laten nemen, of aan anderen ter beschikking te stellen. viaHem wijst iedere aansprakelijkheid voor de inhoud van deze e-mail af. Dat geldt ook voor de mogelijke gevolgen van acties die worden ondernomen op basis van deze informatie.

This email (including any attachments) is confidential, subject to copyright and is sent for the personal attention of the intended recipient only. If you have received this email by mistake, please advise us immediately and delete it. Disclosing, copying or distributing the contents of this e-mail is strictly prohibited. viaHem is not liable for the contents of this email, nor for the consequences of any actions taken on the basis of the information provided in this email or its attachments.
